## Formatting & Processing Data

In [1]:
# libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# read merged_data.csv as new df
merged_data = pd.read_csv("merged_data.csv")

/var/folders/kl/2rx0x22d0j3ckx57rg2j5y_h0000gn/T/ipykernel_18656/3117285008.py:2: DtypeWarning: Columns (0: pain) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_data = pd.read_csv("merged_data.csv")

In [3]:
merged_data

,subject_id,stay_id,seq_num,icd_code,icd_version,icd_title,intime,outtime,gender,race,...,dbp,pain,acuity,chiefcomplaint,charttime_vital,heartrate_vital,resprate_vital,o2sat_vital,sbp_vital,dbp_vital
0,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,68.0,0,3.0,Chest pain,2174-05-26 08:23:00,89.0,31.0,94.0,106.0,64.0
1,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,68.0,0,3.0,Chest pain,2174-05-26 06:46:00,105.0,30.0,95.0,123.0,67.0
2,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,68.0,0,3.0,Chest pain,2174-05-26 06:08:00,104.0,32.0,96.0,124.0,65.0
3,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,68.0,0,3.0,Chest pain,2174-05-26 08:23:00,89.0,31.0,94.0,106.0,64.0
4,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,68.0,0,3.0,Chest pain,2174-05-26 06:46:00,105.0,30.0,95.0,123.0,67.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233955,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,100.0,4,3.0,"s/p Fall, L Shoulder pain",2160-07-16 11:12:00,85.0,25.0,95.0,129.0,77.0
233956,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,100.0,4,3.0,"s/p Fall, L Shoulder pain",2160-07-15 22:45:00,99.0,20.0,96.0,145.0,80.0
233957,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,100.0,4,3.0,"s/p Fall, L Shoulder pain",2160-07-16 03:35:00,87.0,18.0,96.0,104.0,56.0
233958,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,100.0,4,3.0,"s/p Fall, L Shoulder pain",2160-07-16 01:19:00,91.0,20.0,95.0,124.0,72.0
233959,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,100.0,4,3.0,"s/p Fall, L Shoulder pain",2160-07-16 13:50:00,80.0,22.0,94.0,95.0,52.0

In [4]:
# list of columns in merged_data
merged_data.columns

Index(['subject_id', 'stay_id', 'seq_num', 'icd_code', 'icd_version',
       'icd_title', 'intime', 'outtime', 'gender', 'race', 'arrival_transport',
       'disposition', 'charttime', 'med_record', 'gsn_record', 'ndc',
       'etcdescription', 'admmited_charttime', 'adm_med_name', 'gsn_rn',
       'temperature', 'heartrate', 'resprate', 'o2sat', 'sbp', 'dbp', 'pain',
       'acuity', 'chiefcomplaint', 'charttime_vital', 'heartrate_vital',
       'resprate_vital', 'o2sat_vital', 'sbp_vital', 'dbp_vital'],
      dtype='str')

In [5]:
# reformat merged_data to have one row per stay_id, with UNIQUE values in the rest of the columns put in array
reformatted_data = merged_data.groupby('stay_id').agg(lambda x: list(set(x))).reset_index()

In [6]:
reformatted_data

,stay_id,subject_id,seq_num,icd_code,icd_version,icd_title,intime,outtime,gender,race,...,dbp,pain,acuity,chiefcomplaint,charttime_vital,heartrate_vital,resprate_vital,o2sat_vital,sbp_vital,dbp_vital
0,30094124,[10014354],"[1, 2]","[R531, E860]",[10],"[Weakness, Dehydration]",[2147-11-14 18:22:00],[2147-11-14 23:09:00],[M],[WHITE],...,[78.0],[4],[2.0],"[Fatigue, s/p Fall]","[2147-11-14 22:08:00, 2147-11-14 18:23:00]","[80.0, 82.0]",[18.0],"[99.0, 100.0]","[138.0, 142.0]",[78.0]
1,30225689,[10005866],[1],[R109],[10],[Unspecified abdominal pain],[2149-09-20 05:50:00],[2149-09-20 15:53:00],[M],[PORTUGUESE],...,[81.0],[10],[3.0],[Right sided abdominal pain],"[2149-09-20 11:39:00, 2149-09-20 05:50:00, 214...","[72.0, 65.0, 60.0, 77.0]","[16.0, 18.0]","[99.0, 100.0]","[129.0, 138.0, 163.0, 165.0]","[81.0, 75.0, 69.0, 78.0]"
2,30279522,[10014354],[1],[R531],[10],[Weakness],[2149-09-17 09:08:00],[2149-09-17 23:55:00],[M],[WHITE],...,[60.0],[0],[3.0],[Weakness],"[2149-09-17 14:29:00, 2149-09-17 11:54:00, 214...","[72.0, 73.0, 70.0, 71.0]","[16.0, 18.0, 20.0]","[98.0, 99.0, 100.0, 95.0]","[132.0, 134.0, 144.0, 153.0, 122.0, 123.0]","[65.0, 66.0, 57.0, 60.0, 61.0, 62.0]"
3,30373795,[10015860],"[1, 2, 3, 4, 5, 6]","[E119, Z992, N186, M7989, Y832, T82868A]",[10],"[Other specified soft tissue disorders, Anasto...",[2193-05-03 19:12:00],[2193-05-05 02:13:00],[M],[WHITE],...,[64.0],[0],[2.0],"[L Arm numbness, L Arm swelling]","[2193-05-03 22:46:00, 2193-05-04 22:58:00, 219...","[98.0, 99.0, 100.0, 101.0, 92.0, 95.0]","[16.0, 18.0, 20.0]","[96.0, 98.0, 99.0, 100.0]","[137.0, 170.0, 176.0, 146.0, 119.0, 154.0, 156.0]","[64.0, 100.0, 80.0, 88.0, 90.0]"
4,30667562,[10010867],"[1, 2, 3]","[S22059A, S22069A, V499XXA]",[10],"[Unsp fracture of T7-T8 vertebra, init for clo...",[2148-01-25 18:46:00],[2148-01-26 01:27:00],[F],[WHITE - BRAZILIAN],...,[94.0],[0],[2.0],[T-SPINE FX DISPLACEMENT],"[2148-01-25 18:49:00, 2148-01-25 21:14:00, 214...","[104.0, 83.0, 85.0]","[16.0, 18.0]","[97.0, 98.0, 100.0]","[145.0, 146.0, 117.0]","[56.0, 94.0, 71.0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,39740242,[10037928],"[1, 2, 3]","[25001, 5849, 4659]",[9],"[ACUTE KIDNEY FAILURE, UNSPECIFIED, DIABETES U...",[2177-12-21 16:49:00],[2177-12-21 22:26:00],[F],[HISPANIC/LATINO - CUBAN],...,[55.0],[0],[3.0],"[Cough, Dyspnea]","[2177-12-21 20:56:00, 2177-12-21 20:01:00, 217...","[112.0, 105.0, 97.0]","[20.0, 22.0]","[96.0, 97.0, 92.0]","[128.0, 156.0, 148.0]","[56.0, 57.0, 51.0]"
122,39747335,[10039708],"[1, 2]","[M25562, N189]",[10],"[Pain in left knee, Chronic kidney disease, un...",[2142-08-23 16:28:00],[2142-08-23 23:34:00],[F],[BLACK/AFRICAN AMERICAN],...,[83.0],[10],[3.0],[L Knee pain],"[2142-08-23 22:35:00, 2142-08-23 23:32:00, 214...","[80.0, 84.0, 86.0]","[17.0, 18.0]",[100.0],"[113.0, 116.0, 125.0]","[75.0, 83.0, 69.0]"
123,39930808,[10020740],"[1, 2, 3]","[29570, 25000, 78052]",[9],"[DIABETES UNCOMPL ADULT, SCHIZOAFFECTIVE-UNSPE...",[2150-09-15 09:31:00],[2150-09-15 17:09:00],[M],[WHITE],...,[75.0],[0],[3.0],[Insomnia],"[2150-09-15 17:07:00, 2150-09-15 13:37:00]","[83.0, 71.0]",[18.0],[99.0],"[152.0, 129.0]","[85.0, 79.0]"
124,39962121,[10015860],"[1, 2, 3, 4]","[E10621, L97519, Z794, E1065]",[10],"[Type 1 diabetes mellitus with foot ulcer, Typ...",[2191-01-14 21:18:00],[2191-01-15 03:20:00],[M],[WHITE],...,[64.0],[9],[3.0],[R Foot pain],"[2191-01-14 21:41:00, 2191-01-14 21:20:00, 219...","[104.0, 115.0, 117.0, 110.0]","[18.0, 20.0]","[99.0, 100.0]","[105.0, 107.0, 110.0, 121.0, 122.0]","[64.0, 65.0, 58.0, 75.0]"
125,39968716,[10012853],"[1, 2, 3, 4, 5]","[4019, 2720, 25000, 78079, 5990]",[9],"[URIN TRACT INFECTION NOS, DIABETES UNCOMPL AD...",[2176-06-06 13:33:00],[2176-06-06 20:18:00],[F],[BLACK/AFRICAN AMERICAN],...,[43.0],[8],[2.0],"[Dizziness, Weakness]",[2176-06-06 18:23:00],[73.0],[18.0],[98.0],[139.0],[45.0]

In [7]:
# function that calculates difference between each element in charttime and intime
def calculate_time_diff(charttime_list, intime_list):
    time_diffs = []
    for charttime in charttime_list:
        for intime in intime_list:
            time_diff = pd.to_datetime(charttime) - pd.to_datetime(intime)
            time_diffs.append(time_diff.total_seconds() / 3600)  # convert to hours
            # round to three decimal places
            time_diffs[-1] = round(time_diffs[-1], 4)
    return time_diffs

In [8]:
# create new columns charttime_intime_diff and charttime_vital_intime_diff in reformatted_data
reformatted_data['charttime_intime_diff'] = reformatted_data.apply(lambda row: calculate_time_diff(row['charttime'], row['intime']), axis=1)
reformatted_data['charttime_vital_intime_diff'] = reformatted_data.apply(lambda row: calculate_time_diff(row['charttime_vital'], row['intime']), axis=1)

# total time visit
reformatted_data['total_time_visit'] = reformatted_data.apply(lambda row: calculate_time_diff(row['outtime'], row['intime']), axis=1)

# drop charttime and charttime_vital columns
reformatted_data = reformatted_data.drop(columns=['charttime', 'charttime_vital', 'intime', 'outtime'])

In [9]:
reformatted_data

,stay_id,subject_id,seq_num,icd_code,icd_version,icd_title,gender,race,arrival_transport,disposition,...,acuity,chiefcomplaint,heartrate_vital,resprate_vital,o2sat_vital,sbp_vital,dbp_vital,charttime_intime_diff,charttime_vital_intime_diff,total_time_visit
0,30094124,[10014354],"[1, 2]","[R531, E860]",[10],"[Weakness, Dehydration]",[M],[WHITE],[AMBULANCE],[ADMITTED],...,[2.0],"[Fatigue, s/p Fall]","[80.0, 82.0]",[18.0],"[99.0, 100.0]","[138.0, 142.0]",[78.0],[0.4],"[3.7667, 0.0167]",[4.7833]
1,30225689,[10005866],[1],[R109],[10],[Unspecified abdominal pain],[M],[PORTUGUESE],[WALK IN],[ADMITTED],...,[3.0],[Right sided abdominal pain],"[72.0, 65.0, 60.0, 77.0]","[16.0, 18.0]","[99.0, 100.0]","[129.0, 138.0, 163.0, 165.0]","[81.0, 75.0, 69.0, 78.0]","[1.1833, 1.4333, 1.45]","[5.8167, 0.0, 10.0667, 7.8]",[10.05]
2,30279522,[10014354],[1],[R531],[10],[Weakness],[M],[WHITE],[AMBULANCE],[ADMITTED],...,[3.0],[Weakness],"[72.0, 73.0, 70.0, 71.0]","[16.0, 18.0, 20.0]","[98.0, 99.0, 100.0, 95.0]","[132.0, 134.0, 144.0, 153.0, 122.0, 123.0]","[65.0, 66.0, 57.0, 60.0, 61.0, 62.0]",[1.25],"[5.35, 2.7667, 0.0333, 11.2833, 9.5, 13.8667, ...",[14.7833]
3,30373795,[10015860],"[1, 2, 3, 4, 5, 6]","[E119, Z992, N186, M7989, Y832, T82868A]",[10],"[Other specified soft tissue disorders, Anasto...",[M],[WHITE],[AMBULANCE],[HOME],...,[2.0],"[L Arm numbness, L Arm swelling]","[98.0, 99.0, 100.0, 101.0, 92.0, 95.0]","[16.0, 18.0, 20.0]","[96.0, 98.0, 99.0, 100.0]","[137.0, 170.0, 176.0, 146.0, 119.0, 154.0, 156.0]","[64.0, 100.0, 80.0, 88.0, 90.0]",[0.6333],"[3.5667, 27.7667, 11.1167, 25.4167, 8.8667, 18...",[31.0167]
4,30667562,[10010867],"[1, 2, 3]","[S22059A, S22069A, V499XXA]",[10],"[Unsp fracture of T7-T8 vertebra, init for clo...",[F],[WHITE - BRAZILIAN],[AMBULANCE],[ADMITTED],...,[2.0],[T-SPINE FX DISPLACEMENT],"[104.0, 83.0, 85.0]","[16.0, 18.0]","[97.0, 98.0, 100.0]","[145.0, 146.0, 117.0]","[56.0, 94.0, 71.0]",[2.4667],"[0.05, 2.4667, 4.3667]",[6.6833]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,39740242,[10037928],"[1, 2, 3]","[25001, 5849, 4659]",[9],"[ACUTE KIDNEY FAILURE, UNSPECIFIED, DIABETES U...",[F],[HISPANIC/LATINO - CUBAN],[WALK IN],[ADMITTED],...,[3.0],"[Cough, Dyspnea]","[112.0, 105.0, 97.0]","[20.0, 22.0]","[96.0, 97.0, 92.0]","[128.0, 156.0, 148.0]","[56.0, 57.0, 51.0]",[1.3167],"[4.1167, 3.2, 2.0]",[5.6167]
122,39747335,[10039708],"[1, 2]","[M25562, N189]",[10],"[Pain in left knee, Chronic kidney disease, un...",[F],[BLACK/AFRICAN AMERICAN],[WALK IN],[HOME],...,[3.0],[L Knee pain],"[80.0, 84.0, 86.0]","[17.0, 18.0]",[100.0],"[113.0, 116.0, 125.0]","[75.0, 83.0, 69.0]",[3.9833],"[6.1167, 7.0667, 0.0]",[7.1]
123,39930808,[10020740],"[1, 2, 3]","[29570, 25000, 78052]",[9],"[DIABETES UNCOMPL ADULT, SCHIZOAFFECTIVE-UNSPE...",[M],[WHITE],[WALK IN],[HOME],...,[3.0],[Insomnia],"[83.0, 71.0]",[18.0],[99.0],"[152.0, 129.0]","[85.0, 79.0]",[1.2833],"[7.6, 4.1]",[7.6333]
124,39962121,[10015860],"[1, 2, 3, 4]","[E10621, L97519, Z794, E1065]",[10],"[Type 1 diabetes mellitus with foot ulcer, Typ...",[M],[WHITE],[WALK IN],[HOME],...,[3.0],[R Foot pain],"[104.0, 115.0, 117.0, 110.0]","[18.0, 20.0]","[99.0, 100.0]","[105.0, 107.0, 110.0, 121.0, 122.0]","[64.0, 65.0, 58.0, 75.0]",[0.35],"[0.3833, 0.0333, 5.55, 3.1, 4.0167]",[6.0333]
125,39968716,[10012853],"[1, 2, 3, 4, 5]","[4019, 2720, 25000, 78079, 5990]",[9],"[URIN TRACT INFECTION NOS, DIABETES UNCOMPL AD...",[F],[BLACK/AFRICAN AMERICAN],[WALK IN],[ADMITTED],...,[2.0],"[Dizziness, Weakness]",[73.0],[18.0],[98.0],[139.0],[45.0],"[3.9667, 3.95, 4.0167, 4.0, 3.9833]",[4.8333],[6.75]

In [10]:
# columns
reformatted_data.columns

Index(['stay_id', 'subject_id', 'seq_num', 'icd_code', 'icd_version',
       'icd_title', 'gender', 'race', 'arrival_transport', 'disposition',
       'med_record', 'gsn_record', 'ndc', 'etcdescription',
       'admmited_charttime', 'adm_med_name', 'gsn_rn', 'temperature',
       'heartrate', 'resprate', 'o2sat', 'sbp', 'dbp', 'pain', 'acuity',
       'chiefcomplaint', 'heartrate_vital', 'resprate_vital', 'o2sat_vital',
       'sbp_vital', 'dbp_vital', 'charttime_intime_diff',
       'charttime_vital_intime_diff', 'total_time_visit'],
      dtype='str')

In [11]:
# check for missing values in reformatted_data
reformatted_data.isnull().sum()

stay_id                        0
subject_id                     0
seq_num                        0
icd_code                       0
icd_version                    0
icd_title                      0
gender                         0
race                           0
arrival_transport              0
disposition                    0
med_record                     0
gsn_record                     0
ndc                            0
etcdescription                 0
admmited_charttime             0
adm_med_name                   0
gsn_rn                         0
temperature                    0
heartrate                      0
resprate                       0
o2sat                          0
sbp                            0
dbp                            0
pain                           0
acuity                         0
chiefcomplaint                 0
heartrate_vital                0
resprate_vital                 0
o2sat_vital                    0
sbp_vital                      0
dbp_vital                      0
charttime_intime_diff          0
charttime_vital_intime_diff    0
total_time_visit               0
dtype: int64

In [12]:
# save reformatted data as csv
reformatted_data.to_csv("final_clean_data.csv", index=False)

In [13]:
reformatted_data.columns

Index(['stay_id', 'subject_id', 'seq_num', 'icd_code', 'icd_version',
       'icd_title', 'gender', 'race', 'arrival_transport', 'disposition',
       'med_record', 'gsn_record', 'ndc', 'etcdescription',
       'admmited_charttime', 'adm_med_name', 'gsn_rn', 'temperature',
       'heartrate', 'resprate', 'o2sat', 'sbp', 'dbp', 'pain', 'acuity',
       'chiefcomplaint', 'heartrate_vital', 'resprate_vital', 'o2sat_vital',
       'sbp_vital', 'dbp_vital', 'charttime_intime_diff',
       'charttime_vital_intime_diff', 'total_time_visit'],
      dtype='str')

In [14]:
# topics dictionary (nos stands for not otherwise specified)
topics_dict = {
    'sepsis & infection': ['pneumonia,organism unspecified', 'septicemia nos', 'septic shock', 'sever sepsis', 'sepsis', 'bacteremia', 'sepsis, unspecified organism', 'cellulitis of leg', 'cellulitis of foot', 'local skin infection nos', 'cellulitis of left lower limb', 'cellulitis of right toe', 'cellulitis of face', 'urinary tract infection, site not specified', 'urin tract infection nos', 'acute uri nos', 'infec otitis externa nos', 'unspecified viral hepatitis c without hepatic coma', 'asymptomatic hiv infection', 'human immunodeficiency virus [hiv] disease', 'lobar pneumonia, unspecified organism', 'pneumonia, unspecified organism', 'acute laryngitis, without mention of obstruction'],
    'neurological': ['intracerebral hemorrhage', 'grand mal status', 'nontraumatic acute subdural hemorrhage', 'subdural hem w/o coma', 'traum subarachnoid hem', 'traumatic subdural hem', 'nontraumatic subrachnoid heomrrhage, unspecified', 'traum subrac hem w loc of unsp duration, init', 'other convulsions', 'cerebral infractoin, unspecified', 'syncope and collapse', 'encephalopathy, unspecified', 'semicoma/stupor', 'alzheimer\'s disease', 'dementia in conditions classified elsewhere without behaviroal disturbance', 'amyotrophic lateral sclerosis', 'other conditions of brain', 'prsnl hx of tia (tia), and cereb infrc w/o resid deficits', 'tinnitus, left ear', 'dizziness and giddiness', 'vertigo/dizziness', 'headache'],
    'cardiovascular': ['non-st elevation (nstemi) myocardial infraction', 'dissection of unspecified site of aorta', 'atrial fibrillation', 'unspecified atrial fibrillation', 'atrial flutter', 'tachycardia nos', 'shock nos', 'cardiac arrest, cause unspecified', 'diss abdom aortic aneurysm', 'hypotension nos', 'hypotension, unspecified', 'cad unspec vessel, native or graft', 'abn cardiovasc study nec', 'cardiac pacemaker status', 'respiratory arrest', 'saddle embolus of pulmonary artery w/o acute cor pulmonale', 'other pulmonary embolism without acute cor pulmonale', 'long term use antigoagulant', 'long term (current) use of anticoagulants', 'abnormal coagulation profile', 'acute embolism and thrombosis of deep veins of 1 up extrem', 'thrombosis due to vascular prosth dev/grft, init', 'congestive heart failure, unspec', 'heart failure, unspecified', 'unsp combined systolic and diastolic (congestive) hrt fail', 'pericardial effusion (noninflammatory)', 'acute lung edema nos'],
    'hypertension & kidney': ['acute kidney failure, unspecified', 'essential (primary) hypertension', 'hypertension nos', 'chronic kidney disease, stage v', 'chronic kidney disease, unspecified', 'hyp chr kidney disease w stage 5 chr kidney disease or esrd', 'hypertensive chronic kidney disease w stg 1-4/unsp chr kdny', 'end stage renal disease', 'dependence on renal dialysis', 'type 2 diabetes mellitus w diabetic chronic kidney disease', 'displacement of surgically created av fistula, init'],
    'diabetes & metabolic disorders': ['diabetes uncompl adult', 'diabetes uncompl juven', 'diab w manif nec adult', 'iddm w spec manifestation', 'type 1 diabetes mellitus without complications', 'type 2 diabetes mellitus without complications', 'type 1 diabetes mellitus with ketoacidosis without coma', 'diab ketoacidosis iddm', 'diab ketoacidosis adult', 'type 1 diabetes mellituts with hyperglycemia', 'type 2 diabetes mellitus with hyperglycemia', 'type 1 diabetes mellitus with hypoglycemia without coma', 'type 2 diabetes mellitus with hypoglycemia without coma', 'type 1 diabetes mellitus with foot ulcer', 'type 2 diabetes mellitus with foot ulcer', 'long term (current) use of insulin', 'long-term (current) use of insulin', 'long term (current) use of oral hypoglycemic drugs', 'presence of insulin pump (external) (internal)', 'poisoning by insulin and oral hypoglycemic drugs, acc, init', 'hypoglycemia nos', 'hypoglycemia, unspecified', 'acidosis', 'hyposmolality/hypnoatremia', 'hyperkalemia', 'hyperlipidemia, unspecified', 'hypercholesterolemia', 'pure hypercholesterolemia', 'pure hypercholesterolemia, unspecified'],
    'pulmonary & respiratory': ['sarcoidosis of lung', 'dyspnea, unspecified', 'hypoxemia', 'respiratory failure', 'acute respiratory failure', 'other pneumothorax', 'pleural effusion, not elsewhere classified', 'pleural effusion nos', 'respiratory abnorm nec', 'cough'],
    'gastrointenstinal': ['hematemsis', 'gastrointest hemorr nos', 'gastrointestinal hemorrhage, unspecified', 'vasc insuff intest nos', 'acute appendicitis nos', 'unspecified acute appendicitis', 'unspecified intestinal obstruction', 'unsp intestnl obst, unsp as to partial versus complete obst', 'peritoneal abscess', 'unspecified cirrhosis of liver', 'cirrhosis of liver nos', 'oth sequela, chr liv dis', 'acute pancreatitis, unspecified', 'portal vein thrombosis', 'umbilical hernia', 'nausea', 'nausea with vomiting, unspecified', 'diarrhea, unspecified', 'diarrhea', 'epigastric pain', 'right lower quadrant pain', 'unspecified abdominal pain', 'abdominal pain other specied', 'abdominal pain unspec site', 'abdominal pain llq', 'hemorrhage of anus and rectum', 'rectal & anal hemorrhage', 'rectal & anal ulcer', 'other ascites', 'noninf gastroenterit nec'],
    'trauma & injury': ['traum pneumothorax-close', 'fracture three ribs-clos', 'unspecified fall', 'fall on stair/step nec', 'fx dorsal vertebra-close', 'fx lumbar vertebra-close', 'fx c6 vertebra-closed', 'fx mult ribs nos-closed', 'lung contusion-closed', 'liver injury nos', 'adrenal gland injury-cl', 'mv coll w oth obj-driver', 'fracture of symphysis of mandible, init for clos fx', 'lac w/o fb of abd wall, lower left q w penet perit cav, init', 'assault by knife, initial encounter', 'nasal bone fx-closed', 'unsp superficial injury of unsp part of head, init encntr', 'fall (on) (from) unpsecified stairs and steps, init encntr', 'laceration w/o foreign body of oth part of head, init encntr', 'other specified injuries of head, initial encounter', 'fracture of one rib, left side, init for clos fx', 'fracture of bony thorax, part unsp, init for clos fx', 'fall same lev from slip/trio w/o strike against object, init', 'traum subarachnoid hem', 'traumatic subdural hem', 'traum subrac hem w loc of unsp duration, init', 'unsp disp fx of seventh cervical vertebra, init for clos fx', 'unsp fracture of t5-t6 vertebra, init for clos fx', 'unsp fracture of t7-t8 vertebra, init for clos fx', 'fx low radius w ulna-cl', 'fall from other slipping,tripping,stumbling', 'other fall', 'open wound of foot', 'head injury unspecified', 'assault nec', 'accident nos', 'oth places as the place of occurence of the external cause'],
    'oncology': ['secondary malig neo bone', 'malignant neoplasm nos', 'malignant neopl rectum', 'chronic lymphocytic leuk of b-cell type not achieve remis', 'chronic myeloid leuk, bcr/abl-positive, not achieve remis', 'hx of breast malignancy'],
    'mental health & substance use': ['psyhosis nos', 'schizoaffective-unspec', 'insomnia nec', 'major depressive disorder, single episode, unspecified', 'depressive disorder', 'anxiety disorder, unspecified', 'oth psych disorder not due to a sub or known physiol cond', 'suicidal ideations', 'suicidal ideation', 'alcohol withdrawal', 'ac alcohol intox-unspec', 'alcohol abuse with intoxication, unspecified', 'alcohol dependence with withdrawal, unspecified', 'lack of housing'],
    'surgical & procedural complications': ['persist postop fistula', 'comp d/to graft/implant', 'other post-op infection', 'abn react-procedure nos', 'removal vascular catheter', 'anastomos,bypass or grft cause abn react/compl, w/o misadvnt', 'form of external stoma cause abn react/compl, w/o misadvnt', 'oth medical procedures cause abn react/compl, w/o misadvnt', 'oth surgical procedures cause abn react/compl, w/o misadvnt', 'comp d/to gu device/graft', 'other cystostomy complication', 'mech compl of other urinary catheter, initial encounter', 'oth complication of genitourinary prosth dev/grft, init', 'mech compl of infusion catheter, initial encounter', 'oth complication of vascular prosth dev/grft, init', 'misc gastroent and urology devices assoc w incdt, nec', 'encounter for adjustment and management of vad', 'infection following a procedure, initial encounter'],
    'endocrine & thyroid': ['hypothyroidism, unspecified', 'abn lev hormones in specimens from female genital organs'],
    'hematology & immunology': ['anemia, unspecified', 'anemia nos', 'elevated white blood cell count, unspecified', 'other pancytopenia', 'enlarged lyph nodes, unspecified', 'other pancytopenia', 'enlarged lymph nodes, unspecified', 'infarction of spleen', 'sicca syndrome, unspecified'],
    'other': ['cervicalgia', 'chest pain, unspecified', 'other chest pain', 'adv eff medicinal nos', 'adv eff vasodilators nec', 'observation for other specified conditions not found', 'altered mental status', 'unspecified corneal ulcer, right eye', 'visual discomfort, bilateral', 'ocular pain, right eye', 'ocular pain, bilateral', 'conjunctival hemorrhage', 'fever, unspecified', 'other malaise and fatigue', 'other fatigue', 'weakness', 'swelling of limb', 'other disturbances of skin sensation', 'dehydration', 'ulcer of other part of foot', 'non-prs chronic ulcer oth prt right foot w unsp severity', 'non-pressure chronic ulcer oth prt left foot w unsp severity', 'other specified soft tissue disorders', 'dorsalgia, unspecified', 'lumbago', 'low back pain', 'pain in left lower leg', 'pain in left knee', 'joint pain-shlder', 'hematuria, unspecified', 'hypothermia', 'excessive cold nos', 'localized edema', 'nonspec elev of levels of transamns & lactic acid dehydrgnse', 'allergy, unspecified', 'exposure to other specified factors, initial encounter', 'hypotension nos', 'hypotension, unspecified', 'dizziness and giddiness', 'headache']
}

In [15]:
# count number of ICDs for each topic in topics_dict
topic_icd_counts = {topic: len(set(titles)) for topic, titles in topics_dict.items()}
pd.Series(topic_icd_counts).sort_values(ascending=False)

other                                  40
trauma & injury                        37
gastrointenstinal                      30
diabetes & metabolic disorders         29
cardiovascular                         27
sepsis & infection                     23
neurological                           22
surgical & procedural complications    18
mental health & substance use          14
hypertension & kidney                  11
pulmonary & respiratory                10
hematology & immunology                 8
oncology                                6
endocrine & thyroid                     2
dtype: int64

In [16]:
# count the number of times each ICD_title appears in reformatted data
# count the number of times each ICD_title appears in reformatted_data
icd_title_counts = (
    reformatted_data["icd_title"]   # list of titles per stay
    .explode()                      # one title per row
    .astype(str)
    .str.strip()
    .str.lower()
    .value_counts()
)
icd_title_counts_df = icd_title_counts.rename_axis("icd_title").reset_index(name="count")
icd_title_counts_df

                                             icd_title  count
0                   long term (current) use of insulin     14
1                                     hypertension nos     11
2       type 2 diabetes mellitus without complications      8
3                    acute kidney failure, unspecified      8
4                     essential (primary) hypertension      8
..                                                 ...    ...
166                                  pain in left knee      1
167                                       insomnia nec      1
168           type 1 diabetes mellitus with foot ulcer      1
169  non-prs chronic ulcer oth prt right foot w uns...      1
170                          other malaise and fatigue      1

[171 rows x 2 columns]

In [17]:
# Get top 59 most frequent ICD titles
icd_title_counts_df.head(60)

                                            icd_title  count
0                  long term (current) use of insulin     14
1                                    hypertension nos     11
2      type 2 diabetes mellitus without complications      8
3                   acute kidney failure, unspecified      8
4                    essential (primary) hypertension      8
5                              diabetes uncompl adult      7
6                                dyspnea, unspecified      6
7                     unspecified atrial fibrillation      6
8                             chest pain, unspecified      5
9         urinary tract infection, site not specified      5
10     type 1 diabetes mellitus without complications      5
11                                 fever, unspecified      5
12                                           weakness      4
13                        hypothyroidism, unspecified      4
14                           urin tract infection nos      4
15                                atrial fibrillation      4
16                             diabetes uncompl juven      4
17                                        dehydration      3
18              other specified soft tissue disorders      3
19                     pneumonia,organism unspecified      3
20                chronic kidney disease, unspecified      3
21                 long-term (current) use of insulin      3
22                                anemia, unspecified      3
23           gastrointestinal hemorrhage, unspecified      3
24  unspecified viral hepatitis c without hepatic ...      3
25                                    epigastric pain      3
26          long term (current) use of anticoagulants      3
27                                      other fatigue      3
28  fall on same level, unspecified, initial encou...      3
29                               hypercholesterolemia      3
30             pure hypercholesterolemia, unspecified      3
31                         asymptomatic hiv infection      3
32                              altered mental status      3
33                   congestive heart failure, unspec      3
34                         unspecified abdominal pain      2
35                       dependence on renal dialysis      2
36                            end stage renal disease      2
37                          right lower quadrant pain      2
38                  nausea with vomiting, unspecified      2
39       elevated white blood cell count, unspecified      2
40                              diarrhea, unspecified      2
41                       sepsis, unspecified organism      2
42  nonspec elev of levels of transamns & lactic a...      2
43                                           diarrhea      2
44                                   other chest pain      2
45                                              cough      2
46                    pneumonia, unspecified organism      2
47                        long term use antigoagulant      2
48  fall same lev from slip/trip w/o strike agains...      2
49                                   unspecified fall      2
50             pericardial effusion (noninflammatory)      2
51                             cirrhosis of liver nos      2
52  oth places as the place of occurrence of the e...      2
53                      hemorrhage of anus and rectum      2
54                                  cellulitis of leg      2
55                          iddm w spec manifestation      2
56  abn lev hormones in specimens from female geni...      2
57        type 1 diabetes mellitus with hyperglycemia      2
58                             schizoaffective-unspec      2
59  anastomos,bypass or grft cause abn react/compl...      1

In [18]:
baseline_input = reformatted_data.drop(columns=['icd_code', 'subject_id', 'seq_num', 'gsn_record', 'ndc', 'etcdescription', 'gsn_rn'])

In [19]:
import ast
import numpy as np

# Work on baseline_input only; keep icd_title and all other non-listed columns unchanged.

# 1) Drop admmited_charttime
if 'admmited_charttime' in baseline_input.columns:
    baseline_input = baseline_input.drop(columns=['admmited_charttime'])


def _safe_literal_eval(value):
    """Safely parse string-encoded Python literals using ast.literal_eval."""
    try:
        if isinstance(value, str):
            value = value.strip()
            if value == '':
                return np.nan
            return ast.literal_eval(value)
        return value
    except (ValueError, SyntaxError, TypeError):
        return np.nan


def _to_float_list(value):
    """Parse into a list of floats; return np.nan when invalid."""
    parsed = _safe_literal_eval(value)

    if isinstance(parsed, (list, tuple, np.ndarray)):
        out = []
        for x in parsed:
            try:
                out.append(float(x))
            except (TypeError, ValueError):
                continue
        return out if len(out) > 0 else np.nan

    # If already numeric, keep as single-item list
    if isinstance(parsed, (int, float, np.integer, np.floating)):
        return [float(parsed)]

    return np.nan


def _mean_from_list(value):
    """Parse list-like value and flatten to mean float."""
    vals = _to_float_list(value)
    if isinstance(vals, list) and len(vals) > 0:
        return float(np.mean(vals))
    return np.nan


def _single_float(value):
    """Parse single-element list (or numeric) into one float."""
    vals = _to_float_list(value)
    if isinstance(vals, list) and len(vals) > 0:
        return float(vals[0])
    return np.nan


# 2) charttime_intime_diff: keep as parsed float list (array-like), no mean, no NA fill
if 'charttime_vital_intime_diff' in baseline_input.columns:
    baseline_input['charttime_vital_intime_diff'] = baseline_input['charttime_vital_intime_diff'].apply(_to_float_list)

# 3) charttime_vital_intime_diff: same cleaning
if 'charttime_intime_diff' in baseline_input.columns:
    baseline_input['charttime_intime_diff'] = (
        baseline_input['charttime_intime_diff']
        .apply(_mean_from_list)
        .astype(float)
    )
    baseline_input['charttime_intime_diff'] = baseline_input['charttime_intime_diff'].fillna(
        baseline_input['charttime_intime_diff'].median()
    )

# 4) temperature: single-element list string -> float, then fill NA with median
if 'temperature' in baseline_input.columns:
    baseline_input['temperature'] = baseline_input['temperature'].apply(_single_float).astype(float)
    baseline_input['temperature'] = baseline_input['temperature'].fillna(baseline_input['temperature'].median())

# 7) Vital sign columns: parse string-encoded lists into real float lists
vital_list_columns = [
    'heartrate',
    'resprate',
    'o2sat',
    'sbp',
    'dbp',
    'heartrate_vital',
    'resprate_vital',
    'o2sat_vital',
    'sbp_vital',
    'dbp_vital',
]

for col in vital_list_columns:
    if col in baseline_input.columns:
        baseline_input[col] = baseline_input[col].apply(_to_float_list)

In [20]:
baseline_input.columns

Index(['stay_id', 'icd_version', 'icd_title', 'gender', 'race',
       'arrival_transport', 'disposition', 'med_record', 'adm_med_name',
       'temperature', 'heartrate', 'resprate', 'o2sat', 'sbp', 'dbp', 'pain',
       'acuity', 'chiefcomplaint', 'heartrate_vital', 'resprate_vital',
       'o2sat_vital', 'sbp_vital', 'dbp_vital', 'charttime_intime_diff',
       'charttime_vital_intime_diff', 'total_time_visit'],
      dtype='str')

In [21]:
# Clean pain column in baseline_input
if 'pain' in baseline_input.columns:
    def _safe_parse_list(val):
        try:
            if isinstance(val, str):
                val = val.strip()
                if val == '':
                    return []
                parsed = ast.literal_eval(val)
            else:
                parsed = val
        except (ValueError, SyntaxError, TypeError):
            return []

        if isinstance(parsed, (list, tuple, np.ndarray)):
            return list(parsed)
        return [parsed]

    def _clean_pain_element(x):
        try:
            v = float(x)
        except (ValueError, TypeError):
            return np.nan

        if v < 0:
            return np.nan
        if v > 10:
            return 10.0
        return float(v)

    def _pain_mean_from_list(val):
        items = _safe_parse_list(val)
        cleaned = [_clean_pain_element(x) for x in items]

        valid = [x for x in cleaned if not pd.isna(x)]
        if len(valid) == 0:
            return np.nan
        return float(np.mean(valid))

    baseline_input['pain'] = baseline_input['pain'].apply(_pain_mean_from_list).astype(float)

    pain_median = baseline_input['pain'].median()
    baseline_input['pain'] = baseline_input['pain'].fillna(pain_median)

    # Ensure bounded numeric output and no missing values.
    baseline_input['pain'] = baseline_input['pain'].clip(lower=0.0, upper=10.0)

In [22]:
import ast
import numpy as np

# Convert selected list-encoded columns to single float values (first element only)
cols_to_flatten = [
    'temperature',
    'heartrate',
    'resprate',
    'o2sat',
    'sbp',
    'dbp',
    'pain',
    'acuity',
    'icd_version',
    'total_time_visit'
]


def _parse_first_float(value):
    try:
        parsed = ast.literal_eval(value) if isinstance(value, str) else value
    except (ValueError, SyntaxError, TypeError):
        return np.nan

    # Handle list-like parsed values; take first element only.
    if isinstance(parsed, (list, tuple, np.ndarray)):
        if len(parsed) == 0:
            return np.nan
        first = parsed[0]
    else:
        first = parsed

    try:
        return float(first)
    except (ValueError, TypeError):
        return np.nan


for col in cols_to_flatten:
    if col in baseline_input.columns:
        baseline_input[col] = baseline_input[col].apply(_parse_first_float).astype(float)
        baseline_input[col] = baseline_input[col].fillna(baseline_input[col].median())

In [23]:
# 1) Set stay_id as index
if 'stay_id' in baseline_input.columns:
    baseline_input = baseline_input.set_index('stay_id')

# 2) Drop icd_version
if 'icd_version' in baseline_input.columns:
    baseline_input = baseline_input.drop(columns=['icd_version'])

# 3) Create mean/trend features for selected vital/list columns
vital_cols = [
    'heartrate_vital',
    'resprate_vital',
    'o2sat_vital',
    'sbp_vital',
    'dbp_vital',
    'charttime_intime_diff',
    'charttime_vital_intime_diff',
]


def _parse_float_list(value):
    try:
        parsed = ast.literal_eval(value) if isinstance(value, str) else value
    except (ValueError, SyntaxError, TypeError):
        return np.nan

    if isinstance(parsed, (list, tuple, np.ndarray)):
        vals = []
        for x in parsed:
            try:
                vals.append(float(x))
            except (TypeError, ValueError):
                continue
        return vals if len(vals) > 0 else np.nan

    try:
        return [float(parsed)]
    except (TypeError, ValueError):
        return np.nan


def _list_mean(value):
    vals = _parse_float_list(value)
    if isinstance(vals, list) and len(vals) > 0:
        return float(np.mean(vals))
    return np.nan


def _list_trend(value):
    vals = _parse_float_list(value)
    if isinstance(vals, list) and len(vals) > 0:
        return float(vals[-1] - vals[0])
    return np.nan


for col in vital_cols:
    if col in baseline_input.columns:
        mean_col = f"{col}_mean"
        trend_col = f"{col}_trend"

        baseline_input[mean_col] = baseline_input[col].apply(_list_mean).astype(float)
        baseline_input[trend_col] = baseline_input[col].apply(_list_trend).astype(float)

        baseline_input[mean_col] = baseline_input[mean_col].fillna(baseline_input[mean_col].median())
        baseline_input[trend_col] = baseline_input[trend_col].fillna(baseline_input[trend_col].median())

        baseline_input = baseline_input.drop(columns=[col])

In [24]:
from sklearn.preprocessing import LabelEncoder

# Encode selected categorical columns only
categorical_cols = ['gender', 'race', 'arrival_transport', 'disposition']
label_mappings = {}

for col in categorical_cols:
    if col in baseline_input.columns:
        le = LabelEncoder()

        # Treat missing values as their own category
        baseline_input[col] = baseline_input[col].fillna('Unknown').astype(str)

        # Encode in place
        baseline_input[col] = le.fit_transform(baseline_input[col])

        # Build interpretable mapping: label -> integer
        mapping = {label: int(idx) for idx, label in enumerate(le.classes_)}
        label_mappings[col] = mapping

# Print mappings for later interpretation
for col, mapping in label_mappings.items():
    print(f"{col}: {mapping}")

gender: {"['F']": 0, "['M']": 1}
race: {"['BLACK/AFRICAN AMERICAN']": 0, "['HISPANIC/LATINO - CUBAN']": 1, "['HISPANIC/LATINO - SALVADORAN']": 2, "['OTHER']": 3, "['PORTUGUESE']": 4, "['WHITE - BRAZILIAN']": 5, "['WHITE']": 6}
arrival_transport: {"['AMBULANCE']": 0, "['OTHER']": 1, "['UNKNOWN']": 2, "['WALK IN']": 3}
disposition: {"['ADMITTED']": 0, "['ELOPED']": 1, "['HOME']": 2, "['LEFT AGAINST MEDICAL ADVICE']": 3, "['TRANSFER']": 4}

In [25]:
import ast
import re
from collections import Counter

import numpy as np
import pandas as pd

# -------- Helpers --------
def _safe_parse_list(value):
    try:
        parsed = ast.literal_eval(value) if isinstance(value, str) else value
    except (ValueError, SyntaxError, TypeError):
        return []

    if isinstance(parsed, (list, tuple, np.ndarray)):
        return list(parsed)
    if pd.isna(parsed):
        return []
    return [parsed]


def _slugify(name):
    s = str(name).strip().lower()
    s = re.sub(r'[^a-z0-9]+', '_', s)
    s = re.sub(r'_+', '_', s).strip('_')
    return s


# -------- 1) med_record -> top 25 multi-hot --------
if 'med_record' in baseline_input.columns:
    med_lists = baseline_input['med_record'].apply(_safe_parse_list)

    med_counter = Counter()
    for meds in med_lists:
        cleaned = [str(m).strip() for m in meds if str(m).strip()]
        med_counter.update(cleaned)

    top25_med_record = [m for m, _ in med_counter.most_common(25)]

    for med in top25_med_record:
        col_name = f"medrec_{_slugify(med)}"
        baseline_input[col_name] = med_lists.apply(
            lambda meds: int(any(str(x).strip() == med for x in meds))
        ).astype(int)

    baseline_input = baseline_input.drop(columns=['med_record'])

    print('Top 25 med_record medications:')
    print(top25_med_record)


# -------- 2) adm_med_name -> normalized top 15 multi-hot --------
if 'adm_med_name' in baseline_input.columns:
    dose_pattern = re.compile(
        r'\d+(\.\d+)?\s*(mg|mcg|ml|g|%|units?|meq)[^\s]*',
        flags=re.IGNORECASE,
    )
    form_pattern = re.compile(
        r'\b(tab|vial|udcup|btl|soln|cap|inj|susp|syr)\b',
        flags=re.IGNORECASE,
    )

    def _normalize_adm_med(name):
        s = str(name).lower().strip()

        # Specific consolidation mappings BEFORE counting
        if 'morphine' in s:
            return 'morphine'
        if 'hydromorphone' in s:
            return 'hydromorphone'
        if 'ceftriaxone' in s:
            return 'ceftriaxone'
        if 'sodium chloride' in s:
            return 'sodium chloride'
        if 'pantoprazole' in s:
            return 'pantoprazole'
        if 'levothyroxine' in s:
            return 'levothyroxine'

        # Strip dosage-like tokens and form suffix words
        s = dose_pattern.sub(' ', s)
        s = form_pattern.sub(' ', s)

        # Cleanup punctuation/extra whitespace
        s = re.sub(r'[^a-z0-9\s]', ' ', s)
        s = re.sub(r'\s+', ' ', s).strip()
        return s

    adm_lists_raw = baseline_input['adm_med_name'].apply(_safe_parse_list)
    adm_lists_norm = adm_lists_raw.apply(
        lambda meds: [
            _normalize_adm_med(m)
            for m in meds
            if _normalize_adm_med(m) != ''
        ]
    )

    adm_counter = Counter()
    for meds in adm_lists_norm:
        adm_counter.update(meds)

    top15_adm_med = [m for m, _ in adm_counter.most_common(15)]

    for med in top15_adm_med:
        col_name = f"admmed_{_slugify(med)}"
        baseline_input[col_name] = adm_lists_norm.apply(
            lambda meds: int(med in set(meds))
        ).astype(int)

    baseline_input = baseline_input.drop(columns=['adm_med_name'])

    print('Top 15 adm_med_name medications (normalized):')
    print(top15_adm_med)

Top 25 med_record medications:
['furosemide', 'aspirin', 'atorvastatin', 'levothyroxine', 'lisinopril', 'cholecalciferol (vitamin D3)', 'oxycodone', 'metformin', 'pantoprazole', 'multivitamin', 'gabapentin', 'lidocaine', 'melatonin', 'ferrous sulfate', 'fluoxetine', 'docusate sodium', 'magnesium oxide', 'amlodipine', 'losartan', 'sennosides [senna]', 'ziprasidone HCl', 'acyclovir', 'metoprolol succinate', 'omeprazole', 'metoprolol tartrate']
Top 15 adm_med_name medications (normalized):
['morphine', 'acetaminophen', 'ondansetron', 'hydromorphone', 'ceftriaxone', 'furosemide', 'vancomycin', 'pantoprazole', 'levothyroxine', 'aspirin', 'lorazepam', 'dextrose', 'sodium chloride', 'metoprolol tartrate', 'gabapentin']

In [26]:
baseline_input

,icd_title,gender,race,arrival_transport,disposition,temperature,heartrate,resprate,o2sat,sbp,...,admmed_furosemide,admmed_vancomycin,admmed_pantoprazole,admmed_levothyroxine,admmed_aspirin,admmed_lorazepam,admmed_dextrose,admmed_sodium_chloride,admmed_metoprolol_tartrate,admmed_gabapentin
stay_id,,,,,,,,,,,,,,,,,,,,,
30094124,"[Weakness, Dehydration]",1,6,0,0,97.3,80.0,18.0,99.0,138.0,...,0,0,0,0,0,0,0,0,0,0
30225689,[Unspecified abdominal pain],1,4,3,0,97.6,72.0,16.0,100.0,163.0,...,0,0,0,0,0,0,0,0,0,0
30279522,[Weakness],1,6,0,0,98.2,73.0,20.0,99.0,122.0,...,0,0,0,0,1,0,0,0,0,0
30373795,"[Other specified soft tissue disorders, Anasto...",1,6,0,2,98.1,100.0,16.0,100.0,119.0,...,0,0,1,0,1,0,0,0,0,0
30667562,"[Unsp fracture of T7-T8 vertebra, init for clo...",0,5,0,0,99.5,104.0,16.0,100.0,146.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39740242,"[ACUTE KIDNEY FAILURE, UNSPECIFIED, DIABETES U...",0,1,3,0,98.7,108.0,22.0,98.0,151.0,...,0,0,0,0,0,0,0,0,0,0
39747335,"[Pain in left knee, Chronic kidney disease, un...",0,0,3,2,98.5,84.0,17.0,100.0,116.0,...,0,0,0,0,0,0,0,0,0,0
39930808,"[DIABETES UNCOMPL ADULT, SCHIZOAFFECTIVE-UNSPE...",1,6,3,2,98.4,82.0,18.0,99.0,125.0,...,0,0,0,0,0,1,0,0,0,0
39962121,"[Type 1 diabetes mellitus with foot ulcer, Typ...",1,6,3,2,98.2,117.0,20.0,100.0,107.0,...,0,0,0,0,0,0,0,0,0,0
39968716,"[URIN TRACT INFECTION NOS, DIABETES UNCOMPL AD...",0,0,3,0,98.1,77.0,18.0,98.0,100.0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
baseline_input.columns

Index(['icd_title', 'gender', 'race', 'arrival_transport', 'disposition',
       'temperature', 'heartrate', 'resprate', 'o2sat', 'sbp', 'dbp', 'pain',
       'acuity', 'chiefcomplaint', 'total_time_visit', 'heartrate_vital_mean',
       'heartrate_vital_trend', 'resprate_vital_mean', 'resprate_vital_trend',
       'o2sat_vital_mean', 'o2sat_vital_trend', 'sbp_vital_mean',
       'sbp_vital_trend', 'dbp_vital_mean', 'dbp_vital_trend',
       'charttime_intime_diff_mean', 'charttime_intime_diff_trend',
       'charttime_vital_intime_diff_mean', 'charttime_vital_intime_diff_trend',
       'medrec_furosemide', 'medrec_aspirin', 'medrec_atorvastatin',
       'medrec_levothyroxine', 'medrec_lisinopril',
       'medrec_cholecalciferol_vitamin_d3', 'medrec_oxycodone',
       'medrec_metformin', 'medrec_pantoprazole', 'medrec_multivitamin',
       'medrec_gabapentin', 'medrec_lidocaine', 'medrec_melatonin',
       'medrec_ferrous_sulfate', 'medrec_fluoxetine', 'medrec_docusate_sodium',
       'medrec_magnesium_oxide', 'medrec_amlodipine', 'medrec_losartan',
       'medrec_sennosides_senna', 'medrec_ziprasidone_hcl', 'medrec_acyclovir',
       'medrec_metoprolol_succinate', 'medrec_omeprazole',
       'medrec_metoprolol_tartrate', 'admmed_morphine', 'admmed_acetaminophen',
       'admmed_ondansetron', 'admmed_hydromorphone', 'admmed_ceftriaxone',
       'admmed_furosemide', 'admmed_vancomycin', 'admmed_pantoprazole',
       'admmed_levothyroxine', 'admmed_aspirin', 'admmed_lorazepam',
       'admmed_dextrose', 'admmed_sodium_chloride',
       'admmed_metoprolol_tartrate', 'admmed_gabapentin'],
      dtype='str')

In [28]:
# drop chiefcomplaint column in baseline input
baseline_input = baseline_input.drop(columns={'chiefcomplaint'})

In [30]:
# save baseline input as csv file
baseline_input.to_csv("baseline_input.csv", index = True)