# Data Overview

In [677]:
# libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [678]:
# csv reading function for all files in data
def data_reading(file_path):
    data = pd.read_csv("data/" + file_path)
    return data

In [679]:
# read all files in data folder
diagnosis = data_reading("diagnosis.csv")
edstays = data_reading("edstays.csv")
medreconc = data_reading("medrecon.csv")
pyxis = data_reading("pyxis.csv")
triage = data_reading("triage.csv")
vitalsign = data_reading("vitalsign.csv")

patient_info = {
    "diagnosis": diagnosis,
    "edstays": edstays,
    "medreconc": medreconc,
    "pyxis": pyxis,
    "triage": triage,
    "vitalsign": vitalsign
}

In [680]:
# iterate through df and print info and shape
for key, value in patient_info.items():
    print(f"{key} info:")
    print(value.info())
    print(f"{key} shape: {value.shape}")
    print("\n")

diagnosis info:
<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   subject_id   545 non-null    int64
 1   stay_id      545 non-null    int64
 2   seq_num      545 non-null    int64
 3   icd_code     545 non-null    str
 4   icd_version  545 non-null    int64
 5   icd_title    545 non-null    str
dtypes: int64(4), str(2)
memory usage: 25.7 KB
None
diagnosis shape: (545, 6)


edstays info:
<class 'pandas.DataFrame'>
RangeIndex: 222 entries, 0 to 221
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subject_id         222 non-null    int64
 1   hadm_id            172 non-null    float64
 2   stay_id            222 non-null    int64
 3   intime             222 non-null    str
 4   outtime            222 non-null    str
 5   gender             222 non-null    str
 6   race               222 non-null    str
 7   arrival_transport  222 non-null    str
 8   disposition        222 non-null    str
dtypes: float64(1), int64(2), str(6)
memory usage: 15.7 KB
None
edstays shape: (222, 9)


medreconc info:
<class 'pandas.DataFrame'>
RangeIndex: 2764 entries, 0 to 2763
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subject_id      2764 non-null   int64
 1   stay_id         2764 non-null   int64
 2   charttime       2764 non-null   str
 3   name            2764 non-null   str
 4   gsn             2764 non-null   int64
 5   ndc             2764 non-null   int64
 6   etc_rn          2764 non-null   int64
 7   etccode         2760 non-null   float64
 8   etcdescription  2760 non-null   str
dtypes: float64(1), int64(5), str(3)
memory usage: 194.5 KB
None
medreconc shape: (2764, 9)


pyxis info:
<class 'pandas.DataFrame'>
RangeIndex: 1082 entries, 0 to 1081
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   subject_id  1082 non-null   int64
 1   stay_id     1082 non-null   int64
 2   charttime   1082 non-null   str
 3   med_rn      1082 non-null   int64
 4   name        1082 non-null   str
 5   gsn_rn      1082 non-null   int64
 6   gsn         1050 non-null   float64
dtypes: float64(1), int64(4), str(2)
memory usage: 59.3 KB
None
pyxis shape: (1082, 7)


triage info:
<class 'pandas.DataFrame'>
RangeIndex: 222 entries, 0 to 221
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subject_id      222 non-null    int64
 1   stay_id         222 non-null    int64
 2   temperature     196 non-null    float64
 3   heartrate       198 non-null    float64
 4   resprate        199 non-null    float64
 5   o2sat           198 non-null    float64
 6   sbp             199 non-null    float64
 7   dbp             199 non-null    float64
 8   pain            201 non-null    str
 9   acuity          207 non-null    float64
 10  chiefcomplaint  222 non-null    str
dtypes: float64(7), int64(2), str(2)
memory usage: 19.2 KB
None
triage shape: (222, 11)


vitalsign info:
<class 'pandas.DataFrame'>
RangeIndex: 1038 entries, 0 to 1037
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   subject_id   1038 non-null   int64
 1   stay_id      1038 non-null   int64
 2   charttime    1038 non-null   str
 3   temperature  579 non-null    float64
 4   heartrate    1008 non-null   float64
 5   resprate     990 non-null    float64
 6   o2sat        971 non-null    float64
 7   sbp          998 non-null    float64
 8   dbp          998 non-null    float64
 9   rhythm       33 non-null     str
 10  pain         736 non-null    str
dtypes: float64(6), int64(2), str(3)
memory usage: 89.3 KB
None
vitalsign shape: (1038, 11)

In [681]:
diagnosis

,subject_id,stay_id,seq_num,icd_code,icd_version,icd_title
0,10025463,35470228,1,431,9,INTRACEREBRAL HEMORRHAGE
1,10027602,36678718,1,431,9,INTRACEREBRAL HEMORRHAGE
2,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED"
3,10014078,38676365,1,3453,9,GRAND MAL STATUS
4,10007928,39661025,1,5780,9,HEMATEMESIS
...,...,...,...,...,...,...
540,10002428,33978784,1,78009,9,SEMICOMA/STUPOR
541,10002428,32007337,1,78791,9,DIARRHEA
542,10002428,34982171,2,E8889,9,UNSPECIFIED FALL
543,10002428,38216551,1,H5713,10,"Ocular pain, bilateral"
544,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified"

In [682]:
diagnosis_list = diagnosis['icd_title'].str.lower().unique()

In [683]:
diagnosis_list

<StringArray>
[                                    'intracerebral hemorrhage',
                               'pneumonia,organism unspecified',
                                             'grand mal status',
                                                  'hematemesis',
                                      'gastrointest hemorr nos',
                                                  'cervicalgia',
                                      'chest pain, unspecified',
   'saddle embolus of pulmonary artery w/o acute cor pulmonale',
         'other pulmonary embolism without acute cor pulmonale',
                       'nontraumatic acute subdural hemorrhage',
 ...
            'unsp fracture of t7-t8 vertebra, init for clos fx',
          'car driver injured in collision w car in traf, init',
 'car occupant (driver) (passenger) injured in unsp traf, init',
                                         'pleural effusion nos',
                                     'noninf gastroenterit nec',
                                          'respiratory failure',
             'acute laryngitis, without mention of obstruction',
                                    'acute respiratory failure',
                                       'ocular pain, bilateral',
                                  'sicca syndrome, unspecified']
Length: 279, dtype: str

In [684]:
# save diagnosis_list to a text file
with open("diagnosis_list.txt", "w") as f:
    for item in diagnosis_list:
        f.write("%s\n" % item)

In [685]:
# check if all stay_ids are unique in diagnosis
print("Are all stay_ids unique in diagnosis?", diagnosis['stay_id'].is_unique)

# print all duplicate stay_ids in diagnosis and the total number
duplicate_stay_ids = diagnosis[diagnosis.duplicated(subset=['stay_id'], keep=False)]['stay_id']
print("Duplicate stay_ids in diagnosis:", duplicate_stay_ids.unique())
print("Total number of duplicate stay_ids:", len(duplicate_stay_ids.unique()))

Are all stay_ids unique in diagnosis? False
Duplicate stay_ids in diagnosis: [37887480 38926302 37844627 38967799 37323830 38797992 33007927 37593892
 39430108 33693488 39866888 30683757 35942924 36323598 31270431 37578680
 39348852 39738665 30701739 30689793 35766268 31121963 31023359 38319705
 31200743 31353849 36316394 31970687 35958096 38000722 38566596 38433139
 30373795 31626291 31153288 38133986 39962121 39169528 38233644 39930808
 37298974 39346340 39105638 35452640 35203396 39202185 31640785 30094124
 38849383 35205519 39140069 34820898 39633384 36715666 32991451 33563008
 34918384 31612436 30915333 39747335 34604678 36474912 33258284 32952584
 38112554 35968195 39399961 37202404 38237602 34992024 38207210 34478228
 32891808 39740242 37953392 37036523 35156583 39252789 33256413 39968716
 36185653 35933027 39028384 38074673 35547415 37196191 35568186 31254712
 36686656 31764136 34951841 31729614 34922474 34948767 33347721 36976997
 33678912 35087345 31588683 39898790 37321464 37965024 36021274 37206743
 38213541 34205403 31226423 35353291 36132883 31945330 30836087 33922323
 37196722 32840887 31320010 36041505 32095131 39760810 33211001 32405286
 34161260 34391979 36381328 35540249 39910144 32272346 39266792 30193781
 31579293 35114287 39441314 30115213 30667562 32822973 32007337 33227245
 33978784 34982171 38216551]
Total number of duplicate stay_ids: 139

In [686]:
# inspect
duplicate_stays = diagnosis[diagnosis.duplicated(subset=['stay_id'], keep=False)]

In [687]:
duplicate_stays

,subject_id,stay_id,seq_num,icd_code,icd_version,icd_title
11,10014729,37887480,1,0389,9,SEPTICEMIA NOS
12,10014729,37887480,4,78552,9,SEPTIC SHOCK
13,10014729,37887480,2,99592,9,SEVERE SEPSIS
14,10014729,37887480,3,E9479,9,ADV EFF MEDICINAL NOS
15,10004235,38926302,2,2762,9,ACIDOSIS
...,...,...,...,...,...,...
540,10002428,33978784,1,78009,9,SEMICOMA/STUPOR
541,10002428,32007337,1,78791,9,DIARRHEA
542,10002428,34982171,2,E8889,9,UNSPECIFIED FALL
543,10002428,38216551,1,H5713,10,"Ocular pain, bilateral"
544,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified"

In [688]:
# check for exactly duplicate rows in diagnosis
exact_duplicates = diagnosis[diagnosis.duplicated(keep=False)]

In [689]:
exact_duplicates # there are no duplicate rows in diagnosis, and therefore none in duplicate_stays

Empty DataFrame
Columns: [subject_id, stay_id, seq_num, icd_code, icd_version, icd_title]
Index: []

In [690]:
# for every unique stay_id in duplicate_stays, check that there is only one unique subject_id
for stay_id in duplicate_stays['stay_id'].unique():
    subject_ids = duplicate_stays[duplicate_stays['stay_id'] == stay_id]['subject_id'].unique()
    if len(subject_ids) > 1:
        print(f"Stay ID {stay_id} has multiple subject IDs: {subject_ids}")
    else:
        print(f"Stay ID {stay_id} has one unique subject ID: {subject_ids[0]}")

Stay ID 37887480 has one unique subject ID: 10014729
Stay ID 38926302 has one unique subject ID: 10004235
Stay ID 37844627 has one unique subject ID: 10026255
Stay ID 38967799 has one unique subject ID: 10007058
Stay ID 37323830 has one unique subject ID: 10018845
Stay ID 38797992 has one unique subject ID: 10020640
Stay ID 33007927 has one unique subject ID: 10018081
Stay ID 37593892 has one unique subject ID: 10018081
Stay ID 39430108 has one unique subject ID: 10021666
Stay ID 33693488 has one unique subject ID: 10001725
Stay ID 39866888 has one unique subject ID: 10001217
Stay ID 30683757 has one unique subject ID: 10023239
Stay ID 35942924 has one unique subject ID: 10023239
Stay ID 36323598 has one unique subject ID: 10023239
Stay ID 31270431 has one unique subject ID: 10023239
Stay ID 37578680 has one unique subject ID: 10023239
Stay ID 39348852 has one unique subject ID: 10023239
Stay ID 39738665 has one unique subject ID: 10020944
Stay ID 30701739 has one unique subject ID: 10032725
Stay ID 30689793 has one unique subject ID: 10020187
Stay ID 35766268 has one unique subject ID: 10020187
Stay ID 31121963 has one unique subject ID: 10005866
Stay ID 31023359 has one unique subject ID: 10005866
Stay ID 38319705 has one unique subject ID: 10021487
Stay ID 31200743 has one unique subject ID: 10026354
Stay ID 31353849 has one unique subject ID: 10015860
Stay ID 36316394 has one unique subject ID: 10015860
Stay ID 31970687 has one unique subject ID: 10015860
Stay ID 35958096 has one unique subject ID: 10015860
Stay ID 38000722 has one unique subject ID: 10015860
Stay ID 38566596 has one unique subject ID: 10015860
Stay ID 38433139 has one unique subject ID: 10015860
Stay ID 30373795 has one unique subject ID: 10015860
Stay ID 31626291 has one unique subject ID: 10015860
Stay ID 31153288 has one unique subject ID: 10015860
Stay ID 38133986 has one unique subject ID: 10015860
Stay ID 39962121 has one unique subject ID: 10015860
Stay ID 39169528 has one unique subject ID: 10020740
Stay ID 38233644 has one unique subject ID: 10020740
Stay ID 39930808 has one unique subject ID: 10020740
Stay ID 37298974 has one unique subject ID: 10020740
Stay ID 39346340 has one unique subject ID: 10022281
Stay ID 39105638 has one unique subject ID: 10014354
Stay ID 35452640 has one unique subject ID: 10014354
Stay ID 35203396 has one unique subject ID: 10014354
Stay ID 39202185 has one unique subject ID: 10014354
Stay ID 31640785 has one unique subject ID: 10014354
Stay ID 30094124 has one unique subject ID: 10014354
Stay ID 38849383 has one unique subject ID: 10014354
Stay ID 35205519 has one unique subject ID: 10014354
Stay ID 39140069 has one unique subject ID: 10014354
Stay ID 34820898 has one unique subject ID: 10014354
Stay ID 39633384 has one unique subject ID: 10014354
Stay ID 36715666 has one unique subject ID: 10022041
Stay ID 32991451 has one unique subject ID: 10039708
Stay ID 33563008 has one unique subject ID: 10039708
Stay ID 34918384 has one unique subject ID: 10039708
Stay ID 31612436 has one unique subject ID: 10039708
Stay ID 30915333 has one unique subject ID: 10039708
Stay ID 39747335 has one unique subject ID: 10039708
Stay ID 34604678 has one unique subject ID: 10039708
Stay ID 36474912 has one unique subject ID: 10039708
Stay ID 33258284 has one unique subject ID: 10000032
Stay ID 32952584 has one unique subject ID: 10000032
Stay ID 38112554 has one unique subject ID: 10000032
Stay ID 35968195 has one unique subject ID: 10000032
Stay ID 39399961 has one unique subject ID: 10000032
Stay ID 37202404 has one unique subject ID: 10026406
Stay ID 38237602 has one unique subject ID: 10026406
Stay ID 34992024 has one unique subject ID: 10037928
Stay ID 38207210 has one unique subject ID: 10037928
Stay ID 34478228 has one unique subject ID: 10037928
Stay ID 32891808 has one unique subject ID: 10037928
Stay ID 39740242 has one unique subject ID: 10037928
Stay ID 37953392 has one unique subject ID: 10037928
Stay ID 37036523 has one unique subject ID: 10037928
Stay ID 35156583 has one unique subject ID: 10037928
Stay ID 39252789 has one unique subject ID: 10029484
Stay ID 33256413 has one unique subject ID: 10012853
Stay ID 39968716 has one unique subject ID: 10012853
Stay ID 36185653 has one unique subject ID: 10012853
Stay ID 35933027 has one unique subject ID: 10012853
Stay ID 39028384 has one unique subject ID: 10012853
Stay ID 38074673 has one unique subject ID: 10012853
Stay ID 35547415 has one unique subject ID: 10012853
Stay ID 37196191 has one unique subject ID: 10015931
Stay ID 35568186 has one unique subject ID: 10019003
Stay ID 31254712 has one unique subject ID: 10019003
Stay ID 36686656 has one unique subject ID: 10019003
Stay ID 31764136 has one unique subject ID: 10039997
Stay ID 34951841 has one unique subject ID: 10039997
Stay ID 31729614 has one unique subject ID: 10018501
Stay ID 34922474 has one unique subject ID: 10003400
Stay ID 34948767 has one unique subject ID: 10003400
Stay ID 33347721 has one unique subject ID: 10003400
Stay ID 36976997 has one unique subject ID: 10003400
Stay ID 33678912 has one unique subject ID: 10003400
Stay ID 35087345 has one unique subject ID: 10023117
Stay ID 31588683 has one unique subject ID: 10023117
Stay ID 39898790 has one unique subject ID: 10023117
Stay ID 37321464 has one unique subject ID: 10020306
Stay ID 37965024 has one unique subject ID: 10020306
Stay ID 36021274 has one unique subject ID: 10020306
Stay ID 37206743 has one unique subject ID: 10020306
Stay ID 38213541 has one unique subject ID: 10017492
Stay ID 34205403 has one unique subject ID: 10038999
Stay ID 31226423 has one unique subject ID: 10040025
Stay ID 35353291 has one unique subject ID: 10040025
Stay ID 36132883 has one unique subject ID: 10040025
Stay ID 31945330 has one unique subject ID: 10040025
Stay ID 30836087 has one unique subject ID: 10040025
Stay ID 33922323 has one unique subject ID: 10040025
Stay ID 37196722 has one unique subject ID: 10040025
Stay ID 32840887 has one unique subject ID: 10040025
Stay ID 31320010 has one unique subject ID: 10040025
Stay ID 36041505 has one unique subject ID: 10040025
Stay ID 32095131 has one unique subject ID: 10040025
Stay ID 39760810 has one unique subject ID: 10040025
Stay ID 33211001 has one unique subject ID: 10016742
Stay ID 32405286 has one unique subject ID: 10004457
Stay ID 34161260 has one unique subject ID: 10004720
Stay ID 34391979 has one unique subject ID: 10004720
Stay ID 36381328 has one unique subject ID: 10019568
Stay ID 35540249 has one unique subject ID: 10002930
Stay ID 39910144 has one unique subject ID: 10002930
Stay ID 32272346 has one unique subject ID: 10002930
Stay ID 39266792 has one unique subject ID: 10002930
Stay ID 30193781 has one unique subject ID: 10002930
Stay ID 31579293 has one unique subject ID: 10002930
Stay ID 35114287 has one unique subject ID: 10002930
Stay ID 39441314 has one unique subject ID: 10007795
Stay ID 30115213 has one unique subject ID: 10010867
Stay ID 30667562 has one unique subject ID: 10010867
Stay ID 32822973 has one unique subject ID: 10002428
Stay ID 32007337 has one unique subject ID: 10002428
Stay ID 33227245 has one unique subject ID: 10002428
Stay ID 33978784 has one unique subject ID: 10002428
Stay ID 34982171 has one unique subject ID: 10002428
Stay ID 38216551 has one unique subject ID: 10002428

In [691]:
edstays

,subject_id,hadm_id,stay_id,intime,outtime,gender,race,arrival_transport,disposition
0,10014729,23300884.0,37887480,2125-03-19 12:36:00,2125-03-19 16:59:47,F,WHITE - OTHER EUROPEAN,WALK IN,ADMITTED
1,10018328,26706939.0,34176810,2154-02-05 17:09:00,2154-02-05 22:54:00,F,WHITE,AMBULANCE,ADMITTED
2,10018328,NaN,32103106,2154-08-03 15:31:00,2154-08-03 22:29:00,F,WHITE,AMBULANCE,HOME
3,10020640,27984218.0,38797992,2153-02-12 21:59:00,2153-02-13 01:38:00,F,WHITE,AMBULANCE,ADMITTED
4,10015272,27993466.0,33473053,2137-06-12 16:54:00,2137-06-12 18:37:22,F,WHITE,AMBULANCE,ADMITTED
...,...,...,...,...,...,...,...,...,...
217,10009049,22995465.0,31628990,2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,AMBULANCE,ADMITTED
218,10004457,28723315.0,32405286,2141-08-12 12:08:00,2141-08-12 17:20:00,M,WHITE,WALK IN,ADMITTED
219,10004720,22081550.0,34391979,2186-11-12 16:09:00,2186-11-12 19:55:00,M,WHITE,UNKNOWN,ADMITTED
220,10004720,NaN,34161260,2183-12-02 18:06:00,2183-12-03 00:30:00,M,WHITE,WALK IN,HOME
221,10025463,24470193.0,35470228,2137-10-08 18:16:00,2137-10-08 21:20:50,M,WHITE,AMBULANCE,OTHER

In [692]:
# check for missing values in edstays
edstays.isnull().sum()

subject_id            0
hadm_id              50
stay_id               0
intime                0
outtime               0
gender                0
race                  0
arrival_transport     0
disposition           0
dtype: int64

In [693]:
# check if all stay_ids in edstays are unique
print("Are all stay_ids unique in edstays?", edstays['stay_id'].is_unique)

Are all stay_ids unique in edstays? True

In [694]:
# drop hadm_id from edstays
edstays_cleaned = edstays.drop(columns=['hadm_id'])

In [695]:
# merge diagnosis and edstays on stay_id
merged_data = pd.merge(diagnosis, edstays_cleaned, on='stay_id', how='inner')

In [696]:
# drop subject_id_y from merged_data
merged_data = merged_data.drop(columns=['subject_id_y'])
# rename subject_id_x to subject_id
merged_data = merged_data.rename(columns={'subject_id_x': 'subject_id'})

In [697]:
merged_data

,subject_id,stay_id,seq_num,icd_code,icd_version,icd_title,intime,outtime,gender,race,arrival_transport,disposition
0,10025463,35470228,1,431,9,INTRACEREBRAL HEMORRHAGE,2137-10-08 18:16:00,2137-10-08 21:20:50,M,WHITE,AMBULANCE,OTHER
1,10027602,36678718,1,431,9,INTRACEREBRAL HEMORRHAGE,2201-10-30 10:48:00,2201-10-30 12:25:00,F,WHITE,AMBULANCE,ADMITTED
2,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,AMBULANCE,ADMITTED
3,10014078,38676365,1,3453,9,GRAND MAL STATUS,2166-08-21 21:39:00,2166-08-22 00:36:00,F,UNABLE TO OBTAIN,AMBULANCE,ADMITTED
4,10007928,39661025,1,5780,9,HEMATEMESIS,2129-04-05 21:18:00,2129-04-06 00:25:00,F,WHITE,WALK IN,ADMITTED
...,...,...,...,...,...,...,...,...,...,...,...,...
540,10002428,33978784,1,78009,9,SEMICOMA/STUPOR,2156-05-11 11:29:00,2156-05-11 14:49:34,F,WHITE,AMBULANCE,ADMITTED
541,10002428,32007337,1,78791,9,DIARRHEA,2156-04-12 09:56:00,2156-04-12 14:17:27,F,WHITE,WALK IN,ADMITTED
542,10002428,34982171,2,E8889,9,UNSPECIFIED FALL,2157-07-16 01:50:00,2157-07-16 04:11:33,F,WHITE,AMBULANCE,ADMITTED
543,10002428,38216551,1,H5713,10,"Ocular pain, bilateral",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,AMBULANCE,HOME
544,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,AMBULANCE,HOME

In [698]:
# check for all unique values in gender, race, arrival_transport, disposition
print("Unique values in gender column:")
print(merged_data['gender'].unique())
print("\nUnique values in race column:")
print(merged_data['race'].unique())
print("\nUnique values in arrival_transport column:")
print(merged_data['arrival_transport'].unique())
print("\nUnique values in disposition column:")
print(merged_data['disposition'].unique())

Unique values in gender column:
<StringArray>
['M', 'F']
Length: 2, dtype: str

Unique values in race column:
<StringArray>
[                       'WHITE',             'UNABLE TO OBTAIN',
 'HISPANIC/LATINO - SALVADORAN',                      'UNKNOWN',
       'WHITE - OTHER EUROPEAN',      'MULTIPLE RACE/ETHNICITY',
       'BLACK/AFRICAN AMERICAN',                   'PORTUGUESE',
                        'OTHER',      'HISPANIC/LATINO - CUBAN',
   'PATIENT DECLINED TO ANSWER',            'WHITE - BRAZILIAN']
Length: 12, dtype: str

Unique values in arrival_transport column:
<StringArray>
['AMBULANCE', 'WALK IN', 'UNKNOWN', 'OTHER']
Length: 4, dtype: str

Unique values in disposition column:
<StringArray>
[                      'OTHER',                    'ADMITTED',
                        'HOME',                    'TRANSFER',
     'LEFT WITHOUT BEING SEEN', 'LEFT AGAINST MEDICAL ADVICE',
                      'ELOPED']
Length: 7, dtype: str

In [699]:
# check count of each unique value in disposition column
print("Count of each unique value in disposition column:")
print(merged_data['disposition'].value_counts())

Count of each unique value in disposition column:
disposition
ADMITTED                       320
HOME                           196
TRANSFER                        12
LEFT AGAINST MEDICAL ADVICE      7
ELOPED                           6
OTHER                            2
LEFT WITHOUT BEING SEEN          2
Name: count, dtype: int64

In [700]:
merged_data.isnull().sum()

subject_id           0
stay_id              0
seq_num              0
icd_code             0
icd_version          0
icd_title            0
intime               0
outtime              0
gender               0
race                 0
arrival_transport    0
disposition          0
dtype: int64

In [701]:
medreconc

,subject_id,stay_id,charttime,name,gsn,ndc,etc_rn,etccode,etcdescription
0,10023117,31283645,2171-11-07 20:38:00,*acuvite,0,0,1,NaN,NaN
1,10038999,34205403,2132-05-17 21:17:00,*depakote DR,0,0,1,NaN,NaN
2,10002428,38216551,2160-07-15 19:43:00,*nutrient drink,0,0,1,NaN,NaN
3,10016742,33335871,2178-07-22 06:08:00,*iron liquid,0,0,1,NaN,NaN
4,10040025,32034003,2143-03-10 23:20:00,amoxicillin,8996,10544054615,1,3.0,Aminopenicillin Antibiotic
...,...,...,...,...,...,...,...,...,...
2759,10014354,39394858,2148-06-24 15:20:00,hydrocodone-acetaminophen,47430,10544035630,2,6637.0,Analgesic Opioid Hydrocodone and Non-Salicylat...
2760,10015860,38433139,2189-06-05 14:32:00,oxycodone-acetaminophen,4222,10544038228,2,6643.0,Analgesic Opioid Oxycodone and Non-Salicylate ...
2761,10015860,38566596,2188-08-05 22:13:00,oxycodone-acetaminophen,4222,10544038228,2,6643.0,Analgesic Opioid Oxycodone and Non-Salicylate ...
2762,10015860,39962121,2191-01-14 21:39:00,oxycodone-acetaminophen,4222,10544038228,2,6643.0,Analgesic Opioid Oxycodone and Non-Salicylate ...
2763,10015860,37977734,2189-05-23 00:18:00,oxycodone-acetaminophen,4222,10544038228,2,6643.0,Analgesic Opioid Oxycodone and Non-Salicylate ...

In [702]:
# can drop etccode and etc_rn, as class of medication numberwise is not relevant with name, gsn, and ndc
medreconc_cleaned = medreconc.drop(columns=['etccode', 'etc_rn'])

# four missing etcdescription can be filled in manually
# row index 0
medreconc_cleaned.loc[0, 'etcdescription'] = 'Multivitamins, Vision'
# row index 1
medreconc_cleaned.loc[1, 'etcdescription'] = 'Antiepileptic'
# row index 2
medreconc_cleaned.loc[2, 'etcdescription'] = 'Nutritional Supplement'
# row index 3
medreconc_cleaned.loc[3, 'etcdescription'] = 'Antianemics, Iron Supplements, Therapeutic Nutrients'

In [703]:
medreconc_cleaned

,subject_id,stay_id,charttime,name,gsn,ndc,etcdescription
0,10023117,31283645,2171-11-07 20:38:00,*acuvite,0,0,"Multivitamins, Vision"
1,10038999,34205403,2132-05-17 21:17:00,*depakote DR,0,0,Antiepileptic
2,10002428,38216551,2160-07-15 19:43:00,*nutrient drink,0,0,Nutritional Supplement
3,10016742,33335871,2178-07-22 06:08:00,*iron liquid,0,0,"Antianemics, Iron Supplements, Therapeutic Nut..."
4,10040025,32034003,2143-03-10 23:20:00,amoxicillin,8996,10544054615,Aminopenicillin Antibiotic
...,...,...,...,...,...,...,...
2759,10014354,39394858,2148-06-24 15:20:00,hydrocodone-acetaminophen,47430,10544035630,Analgesic Opioid Hydrocodone and Non-Salicylat...
2760,10015860,38433139,2189-06-05 14:32:00,oxycodone-acetaminophen,4222,10544038228,Analgesic Opioid Oxycodone and Non-Salicylate ...
2761,10015860,38566596,2188-08-05 22:13:00,oxycodone-acetaminophen,4222,10544038228,Analgesic Opioid Oxycodone and Non-Salicylate ...
2762,10015860,39962121,2191-01-14 21:39:00,oxycodone-acetaminophen,4222,10544038228,Analgesic Opioid Oxycodone and Non-Salicylate ...
2763,10015860,37977734,2189-05-23 00:18:00,oxycodone-acetaminophen,4222,10544038228,Analgesic Opioid Oxycodone and Non-Salicylate ...

In [704]:
# check count of null values in each column of medreconc
medreconc_cleaned.isnull().sum()

subject_id        0
stay_id           0
charttime         0
name              0
gsn               0
ndc               0
etcdescription    0
dtype: int64

In [705]:
# merge merged_data with medreconc_cleaned on stay_id
merged_data = pd.merge(merged_data, medreconc_cleaned, on='stay_id', how='inner')

In [706]:
# drop subject_id_y from merged_data
merged_data = merged_data.drop(columns=['subject_id_y'])
# rename subject_id_x to subject_id
merged_data = merged_data.rename(columns={'subject_id_x': 'subject_id'})

In [707]:
merged_data

,subject_id,stay_id,seq_num,icd_code,icd_version,icd_title,intime,outtime,gender,race,arrival_transport,disposition,charttime,name,gsn,ndc,etcdescription
0,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,AMBULANCE,ADMITTED,2174-05-26 04:45:00,multivitamin,2524,10770012801,Multivitamins
1,10019777,30952335,1,5789,9,GASTROINTEST HEMORR NOS,2187-02-10 15:11:00,2187-02-10 20:34:00,M,WHITE,AMBULANCE,ADMITTED,2187-02-10 15:32:00,sennosides [senna],19964,10135031401,Laxative - Stimulant
2,10019777,30952335,1,5789,9,GASTROINTEST HEMORR NOS,2187-02-10 15:11:00,2187-02-10 20:34:00,M,WHITE,AMBULANCE,ADMITTED,2187-02-10 15:32:00,docusate sodium [Colace],3009,10135011101,Laxative - Surfactant
3,10019777,30952335,1,5789,9,GASTROINTEST HEMORR NOS,2187-02-10 15:11:00,2187-02-10 20:34:00,M,WHITE,AMBULANCE,ADMITTED,2187-02-10 15:32:00,pantoprazole,27462,13668009705,Gastric Acid Secretion Reducing Agents - Proto...
4,10019777,30952335,1,5789,9,GASTROINTEST HEMORR NOS,2187-02-10 15:11:00,2187-02-10 20:34:00,M,WHITE,AMBULANCE,ADMITTED,2187-02-10 15:32:00,sertraline,46229,13668000601,Antidepressant - Selective Serotonin Reuptake ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7299,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,AMBULANCE,HOME,2160-07-15 19:42:00,Tylenol Extra Strength,4490,10003011501,Analgesic or Antipyretic Non-Opioid
7300,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,AMBULANCE,HOME,2160-07-15 19:42:00,Natural Calcium,1340,10135021101,Minerals and Electrolytes - Calcium Replacement
7301,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,AMBULANCE,HOME,2160-07-15 19:41:00,bupropion HCl,46238,10370016006,Antidepressant-Norepinephrine and Dopamine Reu...
7302,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,AMBULANCE,HOME,2160-07-15 19:42:00,tetrahydrozoline-zinc,48812,10939069711,Ophthalmic - Decongestant-Astringent Combinations
7303,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,AMBULANCE,HOME,2160-07-15 19:41:00,levothyroxine,6650,10544025730,Thyroid Hormones - Synthetic T4 (Thyroxine)

In [708]:
merged_data.isnull().sum()

subject_id           0
stay_id              0
seq_num              0
icd_code             0
icd_version          0
icd_title            0
intime               0
outtime              0
gender               0
race                 0
arrival_transport    0
disposition          0
charttime            0
name                 0
gsn                  0
ndc                  0
etcdescription       0
dtype: int64

In [709]:
pyxis

,subject_id,stay_id,charttime,med_rn,name,gsn_rn,gsn
0,10012853,36185653,2175-04-05 06:39:00,4,Aspirin,1,4380.0
1,10040025,37401157,2145-10-19 23:53:00,2,Aspirin,1,4380.0
2,10014354,30279522,2149-09-17 11:51:00,2,Aspirin,1,4380.0
3,10040025,30836087,2145-07-04 10:27:00,10,Aspirin,1,4380.0
4,10032725,30701739,2143-03-22 21:48:00,2,Aspirin,1,4376.0
...,...,...,...,...,...,...,...
1077,10039708,31612436,2143-09-19 19:51:00,4,Sodium Chloride 0.9% (Mini Bag Plus),1,1210.0
1078,10014354,34617920,2150-05-09 12:22:00,22,Sodium Chloride 0.9% (Mini Bag Plus),1,1210.0
1079,10037928,35156583,2183-08-04 03:22:00,4,Sodium Chloride 0.9% (Mini Bag Plus),1,1210.0
1080,10014354,33222885,2150-04-30 19:43:00,2,Sodium Chloride 0.9% (Mini Bag Plus),1,1210.0
1081,10039708,38488295,2144-01-18 17:29:00,4,Sodium Chloride 0.9% (Mini Bag Plus),1,1210.0

In [710]:
# get info on pyxis
pyxis.info()

<class 'pandas.DataFrame'>
RangeIndex: 1082 entries, 0 to 1081
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   subject_id  1082 non-null   int64
 1   stay_id     1082 non-null   int64
 2   charttime   1082 non-null   str
 3   med_rn      1082 non-null   int64
 4   name        1082 non-null   str
 5   gsn_rn      1082 non-null   int64
 6   gsn         1050 non-null   float64
dtypes: float64(1), int64(4), str(2)
memory usage: 59.3 KB

In [711]:
# drop med_rn, gsn row from pyxis as they are extraneous information
pyxis = pyxis.drop(columns=['med_rn', 'gsn'])

# name column for pyxis and merged_data has to be renamed to avoid confusion in new merged data
pyxis = pyxis.rename(columns={'name': 'adm_med_name'})
merged_data = merged_data.rename(columns={'name': 'med_record'})

# gsn column for pyxis and merged_data has to be renamed to avoid confusion in new merged data
pyxis = pyxis.rename(columns={'gsn': 'adm_gsn'})
merged_data = merged_data.rename(columns={'gsn': 'gsn_record'})

# rename chart time in pyxis to avoid confusion with charttime in merged_data
pyxis = pyxis.rename(columns={'charttime': 'admmited_charttime'})

In [712]:
# merge merged_data with pyxis on stay_id
merged_data = pd.merge(merged_data, pyxis, on='stay_id', how='inner')

In [713]:
merged_data

,subject_id_x,stay_id,seq_num,icd_code,icd_version,icd_title,intime,outtime,gender,race,...,disposition,charttime,med_record,gsn_record,ndc,etcdescription,subject_id_y,admmited_charttime,adm_med_name,gsn_rn
0,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,ADMITTED,2174-05-26 04:45:00,multivitamin,2524,10770012801,Multivitamins,10009049,2174-05-26 08:07:00,Ketorolac,1
1,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,ADMITTED,2174-05-26 04:45:00,multivitamin,2524,10770012801,Multivitamins,10009049,2174-05-26 06:03:00,Vancomycin,1
2,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,ADMITTED,2174-05-26 04:45:00,multivitamin,2524,10770012801,Multivitamins,10009049,2174-05-26 06:03:00,Vancomycin,2
3,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,ADMITTED,2174-05-26 04:45:00,multivitamin,2524,10770012801,Multivitamins,10009049,2174-05-26 06:04:00,OSELTAMivir,1
4,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,ADMITTED,2174-05-26 04:45:00,multivitamin,2524,10770012801,Multivitamins,10009049,2174-05-26 08:07:00,Levofloxacin,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42196,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,HOME,2160-07-15 19:41:00,bupropion HCl,46238,10370016006,Antidepressant-Norepinephrine and Dopamine Reu...,10002428,2160-07-16 08:44:00,Levothyroxine Sodium 25mcg TAB,1
42197,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,HOME,2160-07-15 19:42:00,tetrahydrozoline-zinc,48812,10939069711,Ophthalmic - Decongestant-Astringent Combinations,10002428,2160-07-16 09:36:00,Artificial Tears 15mL DBTL,1
42198,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,HOME,2160-07-15 19:42:00,tetrahydrozoline-zinc,48812,10939069711,Ophthalmic - Decongestant-Astringent Combinations,10002428,2160-07-16 08:44:00,Levothyroxine Sodium 25mcg TAB,1
42199,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,HOME,2160-07-15 19:41:00,levothyroxine,6650,10544025730,Thyroid Hormones - Synthetic T4 (Thyroxine),10002428,2160-07-16 09:36:00,Artificial Tears 15mL DBTL,1
42200,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,HOME,2160-07-15 19:41:00,levothyroxine,6650,10544025730,Thyroid Hormones - Synthetic T4 (Thyroxine),10002428,2160-07-16 08:44:00,Levothyroxine Sodium 25mcg TAB,1

In [714]:
# drop subject_id_y from merged_data_new
merged_data = merged_data.drop(columns=['subject_id_y'])
# rename subject_id_x to subject_id
merged_data = merged_data.rename(columns={'subject_id_x': 'subject_id'})

In [715]:
merged_data.isnull().sum()

subject_id            0
stay_id               0
seq_num               0
icd_code              0
icd_version           0
icd_title             0
intime                0
outtime               0
gender                0
race                  0
arrival_transport     0
disposition           0
charttime             0
med_record            0
gsn_record            0
ndc                   0
etcdescription        0
admmited_charttime    0
adm_med_name          0
gsn_rn                0
dtype: int64

In [716]:
merged_data

,subject_id,stay_id,seq_num,icd_code,icd_version,icd_title,intime,outtime,gender,race,arrival_transport,disposition,charttime,med_record,gsn_record,ndc,etcdescription,admmited_charttime,adm_med_name,gsn_rn
0,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,AMBULANCE,ADMITTED,2174-05-26 04:45:00,multivitamin,2524,10770012801,Multivitamins,2174-05-26 08:07:00,Ketorolac,1
1,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,AMBULANCE,ADMITTED,2174-05-26 04:45:00,multivitamin,2524,10770012801,Multivitamins,2174-05-26 06:03:00,Vancomycin,1
2,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,AMBULANCE,ADMITTED,2174-05-26 04:45:00,multivitamin,2524,10770012801,Multivitamins,2174-05-26 06:03:00,Vancomycin,2
3,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,AMBULANCE,ADMITTED,2174-05-26 04:45:00,multivitamin,2524,10770012801,Multivitamins,2174-05-26 06:04:00,OSELTAMivir,1
4,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,AMBULANCE,ADMITTED,2174-05-26 04:45:00,multivitamin,2524,10770012801,Multivitamins,2174-05-26 08:07:00,Levofloxacin,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42196,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,AMBULANCE,HOME,2160-07-15 19:41:00,bupropion HCl,46238,10370016006,Antidepressant-Norepinephrine and Dopamine Reu...,2160-07-16 08:44:00,Levothyroxine Sodium 25mcg TAB,1
42197,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,AMBULANCE,HOME,2160-07-15 19:42:00,tetrahydrozoline-zinc,48812,10939069711,Ophthalmic - Decongestant-Astringent Combinations,2160-07-16 09:36:00,Artificial Tears 15mL DBTL,1
42198,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,AMBULANCE,HOME,2160-07-15 19:42:00,tetrahydrozoline-zinc,48812,10939069711,Ophthalmic - Decongestant-Astringent Combinations,2160-07-16 08:44:00,Levothyroxine Sodium 25mcg TAB,1
42199,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,AMBULANCE,HOME,2160-07-15 19:41:00,levothyroxine,6650,10544025730,Thyroid Hormones - Synthetic T4 (Thyroxine),2160-07-16 09:36:00,Artificial Tears 15mL DBTL,1
42200,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,AMBULANCE,HOME,2160-07-15 19:41:00,levothyroxine,6650,10544025730,Thyroid Hormones - Synthetic T4 (Thyroxine),2160-07-16 08:44:00,Levothyroxine Sodium 25mcg TAB,1

In [717]:
triage

,subject_id,stay_id,temperature,heartrate,resprate,o2sat,sbp,dbp,pain,acuity,chiefcomplaint
0,10016742,33211001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PICC EVAL
1,10032725,30701739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FACIAL DROOP
2,10010867,30115213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MVC/INTUBATED TRAUMA
3,10004235,38926302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S/P ARREST
4,10027602,36678718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HEAD BLEED
...,...,...,...,...,...,...,...,...,...,...,...
217,10023239,36323598,97.7,111.0,15.0,100.0,133.0,79.0,3,3.0,"Dehydration, Nausea, Rash"
218,10039708,32345277,98.4,106.0,18.0,95.0,131.0,76.0,5,3.0,"Abd pain, Transfer"
219,10012853,35933027,96.8,78.0,16.0,95.0,186.0,66.0,8,3.0,Abd pain
220,10007795,34807453,98.6,108.0,18.0,95.0,143.0,61.0,7,3.0,"Abd pain, Back pain"
221,10037928,35156583,97.8,75.0,16.0,95.0,159.0,60.0,6,3.0,Back pain

In [718]:
triage.info()

<class 'pandas.DataFrame'>
RangeIndex: 222 entries, 0 to 221
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subject_id      222 non-null    int64
 1   stay_id         222 non-null    int64
 2   temperature     196 non-null    float64
 3   heartrate       198 non-null    float64
 4   resprate        199 non-null    float64
 5   o2sat           198 non-null    float64
 6   sbp             199 non-null    float64
 7   dbp             199 non-null    float64
 8   pain            201 non-null    str
 9   acuity          207 non-null    float64
 10  chiefcomplaint  222 non-null    str
dtypes: float64(7), int64(2), str(2)
memory usage: 19.2 KB

In [719]:
# drop rows with missing values in triage
triage = triage.dropna()

In [720]:
# merge merged_data with triage on stay_id
merged_data = pd.merge(merged_data, triage, on='stay_id', how='inner')

In [721]:
merged_data

,subject_id_x,stay_id,seq_num,icd_code,icd_version,icd_title,intime,outtime,gender,race,...,subject_id_y,temperature,heartrate,resprate,o2sat,sbp,dbp,pain,acuity,chiefcomplaint
0,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,10009049,99.0,87.0,18.0,96.0,126.0,68.0,0,3.0,Chest pain
1,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,10009049,99.0,87.0,18.0,96.0,126.0,68.0,0,3.0,Chest pain
2,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,10009049,99.0,87.0,18.0,96.0,126.0,68.0,0,3.0,Chest pain
3,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,10009049,99.0,87.0,18.0,96.0,126.0,68.0,0,3.0,Chest pain
4,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,10009049,99.0,87.0,18.0,96.0,126.0,68.0,0,3.0,Chest pain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39031,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,10002428,98.0,100.0,16.0,97.0,172.0,100.0,4,3.0,"s/p Fall, L Shoulder pain"
39032,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,10002428,98.0,100.0,16.0,97.0,172.0,100.0,4,3.0,"s/p Fall, L Shoulder pain"
39033,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,10002428,98.0,100.0,16.0,97.0,172.0,100.0,4,3.0,"s/p Fall, L Shoulder pain"
39034,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,10002428,98.0,100.0,16.0,97.0,172.0,100.0,4,3.0,"s/p Fall, L Shoulder pain"
39035,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,10002428,98.0,100.0,16.0,97.0,172.0,100.0,4,3.0,"s/p Fall, L Shoulder pain"

In [722]:
merged_data.isnull().sum()

subject_id_x          0
stay_id               0
seq_num               0
icd_code              0
icd_version           0
icd_title             0
intime                0
outtime               0
gender                0
race                  0
arrival_transport     0
disposition           0
charttime             0
med_record            0
gsn_record            0
ndc                   0
etcdescription        0
admmited_charttime    0
adm_med_name          0
gsn_rn                0
subject_id_y          0
temperature           0
heartrate             0
resprate              0
o2sat                 0
sbp                   0
dbp                   0
pain                  0
acuity                0
chiefcomplaint        0
dtype: int64

In [723]:
# drop subject_id_y from merged_data_new
merged_data = merged_data.drop(columns=['subject_id_y'])
# rename subject_id_x to subject_id
merged_data = merged_data.rename(columns={'subject_id_x': 'subject_id'})

In [724]:
vitalsign

,subject_id,stay_id,charttime,temperature,heartrate,resprate,o2sat,sbp,dbp,rhythm,pain
0,10014729,37887480,2125-03-19 13:22:00,NaN,124.0,24.0,100.0,93.0,65.0,NaN,NaN
1,10014729,37887480,2125-03-19 18:28:00,98.9,106.0,18.0,100.0,115.0,70.0,Sinus Tachycardia,5
2,10014729,37887480,2125-03-19 13:07:00,NaN,128.0,18.0,100.0,132.0,96.0,Sinus Tachycardia,NaN
3,10014729,37887480,2125-03-19 16:23:00,99.8,115.0,22.0,97.0,114.0,45.0,Sinus Tachycardia,0
4,10014729,37887480,2125-03-19 13:24:00,NaN,125.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1033,10002428,32822973,2156-04-30 18:47:00,NaN,100.0,30.0,98.0,100.0,55.0,NaN,0
1034,10002428,32822973,2156-04-30 20:14:00,NaN,90.0,26.0,NaN,80.0,41.0,NaN,0
1035,10002428,32822973,2156-04-30 19:47:00,NaN,96.0,29.0,NaN,104.0,56.0,NaN,0
1036,10002428,33227245,2155-12-04 21:31:00,97.4,82.0,16.0,100.0,148.0,85.0,NaN,NaN
1037,10002428,33227245,2155-12-04 21:36:00,97.4,82.0,18.0,100.0,148.0,75.0,NaN,0

In [725]:
# drop temperature, rhythm, and pain, too many missing values
vitalsign = vitalsign.drop(columns=['temperature', 'rhythm', 'pain'])

In [726]:
# check for missing values in vitalsign
vitalsign.isnull().sum()

subject_id     0
stay_id        0
charttime      0
heartrate     30
resprate      48
o2sat         67
sbp           40
dbp           40
dtype: int64

In [727]:
# drop all rows with missing values in vitalsign
vitalsign = vitalsign.dropna()

In [728]:
vitalsign.isnull().sum()

subject_id    0
stay_id       0
charttime     0
heartrate     0
resprate      0
o2sat         0
sbp           0
dbp           0
dtype: int64

In [729]:
vitalsign

,subject_id,stay_id,charttime,heartrate,resprate,o2sat,sbp,dbp
0,10014729,37887480,2125-03-19 13:22:00,124.0,24.0,100.0,93.0,65.0
1,10014729,37887480,2125-03-19 18:28:00,106.0,18.0,100.0,115.0,70.0
2,10014729,37887480,2125-03-19 13:07:00,128.0,18.0,100.0,132.0,96.0
3,10014729,37887480,2125-03-19 16:23:00,115.0,22.0,97.0,114.0,45.0
5,10014729,37887480,2125-03-19 14:00:00,108.0,22.0,97.0,131.0,60.0
...,...,...,...,...,...,...,...,...
1029,10002428,32007337,2156-04-12 10:30:00,126.0,24.0,97.0,135.0,72.0
1030,10002428,32007337,2156-04-12 16:06:00,120.0,28.0,96.0,108.0,55.0
1033,10002428,32822973,2156-04-30 18:47:00,100.0,30.0,98.0,100.0,55.0
1036,10002428,33227245,2155-12-04 21:31:00,82.0,16.0,100.0,148.0,85.0
1037,10002428,33227245,2155-12-04 21:36:00,82.0,18.0,100.0,148.0,75.0

In [730]:
# add _vital to all column names in vitalsign except stay_id and subject_id to avoid confusion in merged_data
vitalsign = vitalsign.rename(columns=lambda x: x + '_vital' if x not in ['stay_id', 'subject_id'] else x)

In [731]:
# merge merged_data with vitalsign on stay_id
merged_data = pd.merge(merged_data, vitalsign, on='stay_id', how = 'inner')

In [ ]:
# drop subject_id_y and rename subject_id_x to subject_id
merged_data = merged_data.drop(columns=['subject_id_y'])
merged_data = merged_data.rename(columns={'subject_id_x': 'subject_id'})

In [734]:
merged_data

,subject_id,stay_id,seq_num,icd_code,icd_version,icd_title,intime,outtime,gender,race,...,dbp,pain,acuity,chiefcomplaint,charttime_vital,heartrate_vital,resprate_vital,o2sat_vital,sbp_vital,dbp_vital
0,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,68.0,0,3.0,Chest pain,2174-05-26 08:23:00,89.0,31.0,94.0,106.0,64.0
1,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,68.0,0,3.0,Chest pain,2174-05-26 06:46:00,105.0,30.0,95.0,123.0,67.0
2,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,68.0,0,3.0,Chest pain,2174-05-26 06:08:00,104.0,32.0,96.0,124.0,65.0
3,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,68.0,0,3.0,Chest pain,2174-05-26 08:23:00,89.0,31.0,94.0,106.0,64.0
4,10009049,31628990,1,486,9,"PNEUMONIA,ORGANISM UNSPECIFIED",2174-05-26 04:20:00,2174-05-26 09:18:00,M,WHITE,...,68.0,0,3.0,Chest pain,2174-05-26 06:46:00,105.0,30.0,95.0,123.0,67.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233955,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,100.0,4,3.0,"s/p Fall, L Shoulder pain",2160-07-16 11:12:00,85.0,25.0,95.0,129.0,77.0
233956,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,100.0,4,3.0,"s/p Fall, L Shoulder pain",2160-07-15 22:45:00,99.0,20.0,96.0,145.0,80.0
233957,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,100.0,4,3.0,"s/p Fall, L Shoulder pain",2160-07-16 03:35:00,87.0,18.0,96.0,104.0,56.0
233958,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,100.0,4,3.0,"s/p Fall, L Shoulder pain",2160-07-16 01:19:00,91.0,20.0,95.0,124.0,72.0
233959,10002428,38216551,3,M3500,10,"Sicca syndrome, unspecified",2160-07-15 17:34:00,2160-07-16 18:49:00,F,WHITE,...,100.0,4,3.0,"s/p Fall, L Shoulder pain",2160-07-16 13:50:00,80.0,22.0,94.0,95.0,52.0

In [735]:
# check number of missing values in each column of merged_data
merged_data.isnull().sum()

subject_id            0
stay_id               0
seq_num               0
icd_code              0
icd_version           0
icd_title             0
intime                0
outtime               0
gender                0
race                  0
arrival_transport     0
disposition           0
charttime             0
med_record            0
gsn_record            0
ndc                   0
etcdescription        0
admmited_charttime    0
adm_med_name          0
gsn_rn                0
temperature           0
heartrate             0
resprate              0
o2sat                 0
sbp                   0
dbp                   0
pain                  0
acuity                0
chiefcomplaint        0
charttime_vital       0
heartrate_vital       0
resprate_vital        0
o2sat_vital           0
sbp_vital             0
dbp_vital             0
dtype: int64

In [736]:
# save merged data as csv
merged_data.to_csv("merged_data.csv", index=False)

In [ ]:
# save merged_data as a tab-delimited txt file
merged_data.to_csv("merged_data.txt", sep='\t', index=False)